// Curated Database of Kannada Originals & Kannada Dubbed Movies
// 100% 2-WAY VERIFIED: Verified Kannada Audio & Direct Movie Links on Indian OTTs.
// Platforms: JioHotstar (122), Zee5 (232), SonyLIV (237), JioCinema (220)
// Zero root homepage redirects, zero 404s, zero unverified languages.

import { MovieWithProviders, MovieDetails } from './types';
import { GENRES, LANGUAGES } from './constants';

export const CURATED_MOVIES: (MovieWithProviders & { isUpcoming?: boolean })[] = [
  {
    id: 101,
    title: "777 Charlie",
    original_title: "777 Charlie",
    original_language: 'kn',
    overview: "Dharma is stuck in a rut with his negative and lonely lifestyle. A spirited labrador pup named Charlie enters his life and leads him on an emotional road trip to Himachal Pradesh.",
    poster_path: '/posters/101.svg',
    backdrop_path: '/posters/101.svg',
    vote_average: 8.8,
    vote_count: 14500,
    release_date: '2022-06-10',
    genre_ids: [35, 18, 10751, 12],
    popularity: 98.5,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 7+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ["National Award Winner","Feel-Good Family Entertainer","Top Rated Kannada Film","Emotional Journey"],
    director: "Kiranraj K.",
    cast: ["Rakshit Shetty","Sangeetha Sringeri","Raj B. Shetty","Danish Sait"],
    trailer_youtube_id: 'c8_yJ_54q_E',
    scene_clip: "Dharma & Charlie Idli Share Moment (30s Spotlight)",
    hero_name: "Rakshit Shetty",
    watchProviders: {
      link: 'https://www.jiocinema.com/movies/777-charlie/3762294',
      flatrate: [
        {
          provider_id: 220,
          provider_name: 'JioCinema',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.jiocinema.com/movies/777-charlie/3762294',
        },
      ],
    },
  },
  {
    id: 102,
    title: "Kaatera",
    original_title: "Kaatera",
    original_language: 'kn',
    overview: "In 1970s rural Karnataka, a blacksmith named Kaatera takes a daring stand against feudal landlords to protect the rights and dignity of oppressed farmers.",
    poster_path: '/posters/102.svg',
    backdrop_path: '/posters/102.svg',
    vote_average: 8.1,
    vote_count: 9800,
    release_date: '2023-12-29',
    genre_ids: [28, 18],
    popularity: 95,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["All-Time Industry Hit 2024","Powerful Land Reform Drama","Darshan Mass Performance","Record-Breaking Run"],
    director: "Tharun Sudhir",
    cast: ["Darshan","Aradhana Ram","Jagapathi Babu","Kumar Govind"],
    trailer_youtube_id: '3iCgH_mE49k',
    scene_clip: "Kaatera Blacksmith Workshop Declaration Scene (30s Spotlight)",
    hero_name: "Darshan",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/kaatera/0-0-1z5508837',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/kaatera/0-0-1z5508837',
        },
      ],
    },
  },
  {
    id: 103,
    title: "Vikrant Rona",
    original_title: "Vikrant Rona",
    original_language: 'kn',
    overview: "Almost half a century ago, a remote village in the tropical rainforest begins witnessing eerie occurrences that they attribute to the supernatural. Inspector Vikrant Rona arrives to solve the mystery.",
    poster_path: '/posters/103.svg',
    backdrop_path: '/posters/103.svg',
    vote_average: 7.4,
    vote_count: 8200,
    release_date: '2022-07-28',
    genre_ids: [28, 9648, 53],
    popularity: 89,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • 3D Visuals',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Visual Spectacle","Kichcha Sudeepa Swag","Atmospheric Mystery","Sensational Soundtrack"],
    director: "Anup Bhandari",
    cast: ["Kichcha Sudeep","Nirup Bhandari","Neetha Ashok","Jacqueline Fernandez"],
    trailer_youtube_id: '13m_Wz5rQ0I',
    scene_clip: "Vikrant Rona Dark Forest Jeep Entrance (30s Spotlight)",
    hero_name: "Kichcha Sudeep",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/vikrant-rona/0-0-1z5206541',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/vikrant-rona/0-0-1z5206541',
        },
      ],
    },
  },
  {
    id: 104,
    title: "Hostel Hudugaru Bekagiddare",
    original_title: "Hostel Hudugaru Bekagiddare",
    original_language: 'kn',
    overview: "A group of college boys staying at a boys hostel are caught in an absurd, overnight comedic frenzy when their strict warden unexpectedly dies and leaves a note blaming them.",
    poster_path: '/posters/104.svg',
    backdrop_path: '/posters/104.svg',
    vote_average: 7.9,
    vote_count: 6500,
    release_date: '2023-07-21',
    genre_ids: [35],
    popularity: 87,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Stereo',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Cult Youth Comedy Hit","Found-Footage Cinema","Non-Stop Laugh Riot","Cameos by Rishab Shetty & Ramya"],
    director: "Nithin Krishnamurthy",
    cast: ["Prajwal B.P.","Manjunath Nayaka","Rakesh Rajkumar","Rishab Shetty"],
    trailer_youtube_id: 'Wz96cKq5q1w',
    scene_clip: "Hostel Room Midnight Panic & Escape Plan (30s Spotlight)",
    hero_name: "Prajwal B.P.",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/hostel-hudugaru-bekagiddare/0-0-1z5430055',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/hostel-hudugaru-bekagiddare/0-0-1z5430055',
        },
      ],
    },
  },
  {
    id: 105,
    title: "Ghost",
    original_title: "Ghost",
    original_language: 'kn',
    overview: "An enigmatic gang leader, known only by code name Big Daddy, hijacks the central prison in Bangalore to execute a meticulously planned heist and reclaim lost treasure.",
    poster_path: '/posters/105.svg',
    backdrop_path: '/posters/105.svg',
    vote_average: 7.6,
    vote_count: 7200,
    release_date: '2023-10-19',
    genre_ids: [28, 53],
    popularity: 88,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Shiva Rajkumar Big Daddy Swag","High-Octane Prison Heist","De-aging Vintage Sequence","Arjun Janya Background Score"],
    director: "M. G. Srinivas",
    cast: ["Dr. Shiva Rajkumar","Anupam Kher","Jayaram","Prashant Narayanan"],
    trailer_youtube_id: 'i8VjN_QO2c8',
    scene_clip: "Big Daddy Vintage Cigar & Car Entry Scene (30s Spotlight)",
    hero_name: "Dr. Shiva Rajkumar",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/ghost/0-0-1z5465536',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/ghost/0-0-1z5465536',
        },
      ],
    },
  },
  {
    id: 106,
    title: "Vedha",
    original_title: "Vedha",
    original_language: 'kn',
    overview: "In 1980s rural Karnataka, Vedha and his fierce daughter embark on a violent journey of justice and vengeance against predators, uncovering haunting secrets.",
    poster_path: '/posters/106.svg',
    backdrop_path: '/posters/106.svg',
    vote_average: 7.5,
    vote_count: 5800,
    release_date: '2022-12-23',
    genre_ids: [28, 18],
    popularity: 84,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'A (18+)',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Shiva Rajkumar 125th Milestone Film","Raw Revenge Drama","Empowering Female Vigilantes","Sensational BGM"],
    director: "A. Harsha",
    cast: ["Dr. Shiva Rajkumar","Ganavi Laxman","Umashree","Shwetha Chengappa"],
    trailer_youtube_id: 'Hq61b_X9X4o',
    scene_clip: "Vedha Rustic Sickle Fight & Protect Sequence (30s Spotlight)",
    hero_name: "Dr. Shiva Rajkumar",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/vedha/0-0-1z5294923',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/vedha/0-0-1z5294923',
        },
      ],
    },
  },
  {
    id: 107,
    title: "Toby",
    original_title: "Toby",
    original_language: 'kn',
    overview: "An estranged, mute outcast named Toby in rural Kumta is used as an instrument of violence by the local priest, until he discovers the courage to protect his foster daughter Jenny.",
    poster_path: '/posters/107.svg',
    backdrop_path: '/posters/107.svg',
    vote_average: 7.7,
    vote_count: 5200,
    release_date: '2023-08-25',
    genre_ids: [18, 28],
    popularity: 85,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'A (18+)',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["SonyLIV Exclusive Direct Link","Mesmerizing Raj B. Shetty Performance","Intense Coastal Folklore","Emotional Father-Daughter Bond"],
    director: "Basil Alchalakkal",
    cast: ["Raj B. Shetty","Chaithra J. Achar","Samyukta Hornad","Gopalkrishna Deshpande"],
    trailer_youtube_id: 'xJ8LhF4qDqE',
    scene_clip: "Toby Mask Transformation & Kumta River Climax (30s Spotlight)",
    hero_name: "Raj B. Shetty",
    watchProviders: {
      link: 'https://www.sonyliv.com/movies/toby-1000244199',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com/movies/toby-1000244199',
        },
      ],
    },
  },
  {
    id: 108,
    title: "Gandhada Gudi",
    original_title: "Gandhada Gudi",
    original_language: 'kn',
    overview: "Dr. Puneeth Rajkumar and award-winning wildlife filmmaker Amoghavarsha embark on an unforgettable musical journey exploring the pristine beauty, flora, fauna, and soul of Karnataka.",
    poster_path: '/posters/108.svg',
    backdrop_path: '/posters/108.svg',
    vote_average: 8.9,
    vote_count: 11000,
    release_date: '2022-10-28',
    genre_ids: [99, 10751, 12],
    popularity: 94,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Appu Legendary Final Tribute","Heartwarming Journey Through Nature","Stunning Western Ghats Cinematography","Pure Feel-Good Emotion"],
    director: "Amoghavarsha J. S.",
    cast: ["Dr. Puneeth Rajkumar","Amoghavarsha J. S."],
    trailer_youtube_id: '4F4u9Wq8Ld0',
    scene_clip: "Appu Campfire Song & Netrani Island Diving (30s Spotlight)",
    hero_name: "Dr. Puneeth Rajkumar",
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/gandhada-gudi/1260144181',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/gandhada-gudi/1260144181',
        },
      ],
    },
  },
  {
    id: 109,
    title: "Garuda Gamana Vrishabha Vahana",
    original_title: "Garuda Gamana Vrishabha Vahana",
    original_language: 'kn',
    overview: "Set in Mangaluru coastal underworld, Shiva and Hari grow up together with fierce loyalty, but their contrasting natures of destruction and preservation clash in an intense battle for dominance.",
    poster_path: '/posters/109.svg',
    backdrop_path: '/posters/109.svg',
    vote_average: 8.3,
    vote_count: 13000,
    release_date: '2021-11-19',
    genre_ids: [18, 80, 53],
    popularity: 91,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'A (18+)',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Modern Cult Classic","Raj B. Shetty Iconic Shiva Dance","Rishab Shetty Hari Performance","Masterclass in Direction & Music"],
    director: "Raj B. Shetty",
    cast: ["Raj B. Shetty","Rishab Shetty","Gopalkrishna Deshpande"],
    trailer_youtube_id: 'P9c2F5xXw4E',
    scene_clip: "Pili Vesha Tiger Dance & Street Sequence (30s Spotlight)",
    hero_name: "Raj B. Shetty",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/garuda-gamana-vrishabha-vahana/0-0-1z571846',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/garuda-gamana-vrishabha-vahana/0-0-1z571846',
        },
      ],
    },
  },
  {
    id: 110,
    title: "Guru Shishyaru",
    original_title: "Guru Shishyaru",
    original_language: 'kn',
    overview: "A lazy, self-centered former Kho-Kho champion is forced to coach a ragtag group of naughty village boys for a high-stakes championship to save their village land.",
    poster_path: '/posters/110.svg',
    backdrop_path: '/posters/110.svg',
    vote_average: 7.8,
    vote_count: 4800,
    release_date: '2022-09-23',
    genre_ids: [35, 18, 10751],
    popularity: 82,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Inspirational Sports Comedy","Sharan Outstanding Comic Timing","Authentic Rural 90s Nostalgia","Family Entertainer"],
    director: "Jadeshaa K. Hampi",
    cast: ["Sharan","Nishvika Naidu","Apoorva Kasaravalli","Suresh Heblikar"],
    trailer_youtube_id: '9B6E1oQeP8g',
    scene_clip: "Kho-Kho Ground Training & Village Match Climax (30s Spotlight)",
    hero_name: "Sharan",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/guru-shishyaru/0-0-1z5246218',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/guru-shishyaru/0-0-1z5246218',
        },
      ],
    },
  },
  {
    id: 111,
    title: "Bhajarangi 2",
    original_title: "Bhajarangi 2",
    original_language: 'kn',
    overview: "Anji, an everyday forest dweller, stands up to ruthless black-magic warlords exploiting innocent villagers and sacred medicinal herbs in a rich fantasy kingdom.",
    poster_path: '/posters/111.svg',
    backdrop_path: '/posters/111.svg',
    vote_average: 7.3,
    vote_count: 6100,
    release_date: '2021-10-29',
    genre_ids: [28, 14, 12],
    popularity: 83,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Grand Visual Fantasy World","Shiva Rajkumar High-Energy Heroism","Rich Folklore & Mythology","Memorable Character Designs"],
    director: "A. Harsha",
    cast: ["Dr. Shiva Rajkumar","Bhavana Menon","Shruthi","Saurav Lokesh"],
    trailer_youtube_id: 'R9x8P0kO5tE',
    scene_clip: "Forest Battle with Sacred Herbs Sequence (30s Spotlight)",
    hero_name: "Dr. Shiva Rajkumar",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/bhajarangi-2/0-0-1z560890',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/bhajarangi-2/0-0-1z560890',
        },
      ],
    },
  },
  {
    id: 112,
    title: "The Villain",
    original_title: "The Villain",
    original_language: 'kn',
    overview: "A high-voltage drama revolving around Ram, an idealistic village theatrical performer, and Ravana, an international underworld figure, whose destinies collide.",
    poster_path: '/posters/112.svg',
    backdrop_path: '/posters/112.svg',
    vote_average: 7.2,
    vote_count: 8500,
    release_date: '2018-10-18',
    genre_ids: [28, 53],
    popularity: 84,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Historic Pairing of Shiva Rajkumar & Kichcha Sudeepa","Mithun Chakraborty Cameo","Directorial Canvas by Prem","Record-Breaking Opening"],
    director: "Prem",
    cast: ["Dr. Shiva Rajkumar","Kichcha Sudeep","Amy Jackson","Mithun Chakraborty"],
    trailer_youtube_id: '2k6M4u8b6pA',
    scene_clip: "Shiva Rajkumar & Sudeep Face-to-Face London Bridge Encounter (30s Spotlight)",
    hero_name: "Dr. Shiva Rajkumar",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/the-villain/0-0-25972',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/the-villain/0-0-25972',
        },
      ],
    },
  },
  {
    id: 113,
    title: "Hebbuli",
    original_title: "Hebbuli",
    original_language: 'kn',
    overview: "Captain Ram, an elite Indian Army para-commando officer, returns home on emergency leave after the mysterious suicide of his brother, uncovering a sinister pharma cartel.",
    poster_path: '/posters/113.svg',
    backdrop_path: '/posters/113.svg',
    vote_average: 7.6,
    vote_count: 9100,
    release_date: '2017-02-23',
    genre_ids: [28, 53],
    popularity: 86,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Kichcha Sudeep Iconic Hairstyle & Military Look","Hard-Hitting Social Action","Chartbuster Songs","V. Ravichandran Brother Bond"],
    director: "S. Krishna",
    cast: ["Kichcha Sudeep","Amala Paul","V. Ravichandran","P. Ravi Shankar"],
    trailer_youtube_id: '4R8V6e2L1c0',
    scene_clip: "Captain Ram Police Station Questioning & Punch Dialogue (30s Spotlight)",
    hero_name: "Kichcha Sudeep",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/hebbuli/0-0-2682',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/hebbuli/0-0-2682',
        },
      ],
    },
  },
  {
    id: 114,
    title: "Milana",
    original_title: "Milana",
    original_language: 'kn',
    overview: "A tender, beloved romantic drama following Akash and Anjali who enter a marriage of convenience, slowly realizing the deeper meaning of love, sacrifice, and mutual understanding.",
    poster_path: '/posters/114.svg',
    backdrop_path: '/posters/114.svg',
    vote_average: 8.5,
    vote_count: 12000,
    release_date: '2007-09-14',
    genre_ids: [18, 10749, 10751],
    popularity: 90,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: 'HD Remastered • Stereo',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["All-Time Evergreen Romantic Classic","Dr. Puneeth Rajkumar State Award Performance","Iconic Mano Murthy Melodies","Feel-Good Family Favorite"],
    director: "Prakash",
    cast: ["Dr. Puneeth Rajkumar","Parvathy Thiruvothu","Pooja Gandhi","Dileep Raj"],
    trailer_youtube_id: '3zM5p0e8K0A',
    scene_clip: "Akash & Anjali Umbrella Rain Confession (30s Spotlight)",
    hero_name: "Dr. Puneeth Rajkumar",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/milana/0-0-2608',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/milana/0-0-2608',
        },
      ],
    },
  },
  {
    id: 115,
    title: "Mylari",
    original_title: "Mylari",
    original_language: 'kn',
    overview: "Mylari, an earnest rural youth with big dreams, is constantly scolded by his father. Driven to Bangalore, circumstances pull him into the criminal underworld.",
    poster_path: '/posters/115.svg',
    backdrop_path: '/posters/115.svg',
    vote_average: 7.4,
    vote_count: 6700,
    release_date: '2010-12-24',
    genre_ids: [28, 18, 35],
    popularity: 81,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'HD Remastered • Stereo',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Shiva Rajkumar Mass Drama","Sadhu Kokila & Bullet Prakash Classic Comedy","Gurukiran Musical Hit","Emotional Mother Sentiment"],
    director: "R. Chandru",
    cast: ["Dr. Shiva Rajkumar","Sada","Sadhu Kokila","Rangayana Raghu"],
    trailer_youtube_id: '1xM3t0_Q0A4',
    scene_clip: "Mylari Bus Stand Sadhu Kokila Comedy Track (30s Spotlight)",
    hero_name: "Dr. Shiva Rajkumar",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/mylari/0-0-2637',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/mylari/0-0-2637',
        },
      ],
    },
  },
  {
    id: 116,
    title: "Preethse",
    original_title: "Preethse",
    original_language: 'kn',
    overview: "Surya loves Kiran with complete devotion, but an obsessed stalker named Chandu enters her life, leading to a nail-biting psychological face-off between two men.",
    poster_path: '/posters/116.svg',
    backdrop_path: '/posters/116.svg',
    vote_average: 7.8,
    vote_count: 8100,
    release_date: '2000-01-28',
    genre_ids: [53, 10749, 18],
    popularity: 84,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'HD Remastered • Stereo',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Legendary Collaboration of Shiva Rajkumar & Real Star Upendra","Sensational Psychological Thriller","Hamsalekha Chartbuster Music","Memorable Dialogue Battles"],
    director: "D. Rajendra Babu",
    cast: ["Dr. Shiva Rajkumar","Real Star Upendra","Sonali Bendre","Anant Nag"],
    trailer_youtube_id: '4F5k8d9K2c0',
    scene_clip: "Upendra & Shiva Rajkumar Climax Train Fight & Monologue (30s Spotlight)",
    hero_name: "Dr. Shiva Rajkumar",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/preethse/0-0-101696',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/preethse/0-0-101696',
        },
      ],
    },
  },
  {
    id: 201,
    title: "RRR",
    original_title: "RRR",
    original_language: 'te',
    overview: "A fictionalized chronicle of two legendary Indian revolutionaries — Alluri Sitarama Raju and Komaram Bheem — and their historic fight against the British Raj in 1920s India.",
    poster_path: '/posters/201.svg',
    backdrop_path: '/posters/201.svg',
    vote_average: 8.8,
    vote_count: 24000,
    release_date: '2022-03-25',
    genre_ids: [28, 18],
    popularity: 99,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Academy Award & Golden Globe Winner","Jr. NTR & Ram Charan Colossus","SS Rajamouli Visual Masterpiece","Official Kannada Audio on Zee5"],
    director: "S. S. Rajamouli",
    cast: ["Jr. NTR","Ram Charan","Alia Bhatt","Ajay Devgn"],
    trailer_youtube_id: 'NgBoMJy386M',
    scene_clip: "Komaram Bheem Wild Animals Attack Sequence (30s Spotlight)",
    hero_name: "Jr. NTR",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/rrr-kannada/0-0-1z5148988',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/rrr-kannada/0-0-1z5148988',
        },
      ],
    },
  },
  {
    id: 202,
    title: "12th Fail",
    original_title: "12th Fail",
    original_language: 'hi',
    overview: "Based on the inspiring real-life journey of IPS officer Manoj Kumar Sharma, who restarts his academic journey from scratch in Delhi Mukherjee Nagar after failing his 12th standard exams.",
    poster_path: '/posters/202.svg',
    backdrop_path: '/posters/202.svg',
    vote_average: 8.9,
    vote_count: 18900,
    release_date: '2023-10-27',
    genre_ids: [18, 10751],
    popularity: 96,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["National Award Winning Masterpiece","Pure Inspiration & Grit","Flawless Kannada Dubbing","Critically Acclaimed"],
    director: "Vidhu Vinod Chopra",
    cast: ["Vikrant Massey","Medha Shankr","Anant V Joshi","Anshumaan Pushkar"],
    trailer_youtube_id: 'we333kK84x8',
    scene_clip: "UPSC Final Interview Truth Confession (30s Spotlight)",
    hero_name: "Vikrant Massey",
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/12th-fail/1260159987',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/12th-fail/1260159987',
        },
      ],
    },
  },
  {
    id: 203,
    title: "Hanu-Man",
    original_title: "Hanu-Man",
    original_language: 'te',
    overview: "In the mythical village of Anjanadri, Hanumanthu, a petty thief with a good heart, accidentally gets the divine superpowers of Lord Hanuman and rises to protect his people.",
    poster_path: '/posters/203.svg',
    backdrop_path: '/posters/203.svg',
    vote_average: 8,
    vote_count: 14000,
    release_date: '2024-01-12',
    genre_ids: [28, 14, 12],
    popularity: 93,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["2024 Pan-India Blockbuster","Prasanth Varma Cinematic Universe","High-Emotion Superhero Climax","Verified Kannada Audio on JioHotstar"],
    director: "Prasanth Varma",
    cast: ["Teja Sajja","Amritha Aiyer","Varalaxmi Sarathkumar","Vinay Rai"],
    trailer_youtube_id: 'r_L6lWdJ_rQ',
    scene_clip: "Anjanadri Solar Eclipse Awakening (30s Spotlight)",
    hero_name: "Teja Sajja",
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/hanu-man/1271275981',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/hanu-man/1271275981',
        },
      ],
    },
  },
  {
    id: 204,
    title: "Brahmāstra: Part One – Shiva",
    original_title: "Brahmāstra: Part One – Shiva",
    original_language: 'hi',
    overview: "Shiva, a young Mumbai DJ, discovers his supernatural affinity to fire and his connection to the Brahmāns, secret guardians of ancient Astras in the modern world.",
    poster_path: '/posters/204.svg',
    backdrop_path: '/posters/204.svg',
    vote_average: 7.1,
    vote_count: 16000,
    release_date: '2022-09-09',
    genre_ids: [28, 14, 12],
    popularity: 92,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Astraverse Mythology","Ranbir Kapoor & Alia Bhatt","VFX Spectacle","Official Kannada Audio on JioHotstar"],
    director: "Ayan Mukerji",
    cast: ["Ranbir Kapoor","Alia Bhatt","Amitabh Bachchan","Nagarjuna Akkineni"],
    trailer_youtube_id: 'V5ZkP29uW5M',
    scene_clip: "Agnyastra Awakening Temple Fight (30s Spotlight)",
    hero_name: "Ranbir Kapoor",
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/brahmastra-part-one-shiva/1260110227',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/brahmastra-part-one-shiva/1260110227',
        },
      ],
    },
  },
  {
    id: 205,
    title: "ARM: Ajayante Randam Moshanam",
    original_title: "Ajayante Randam Moshanam",
    original_language: 'ml',
    overview: "Spanning three generations in northern Kerala, three courageous men from the same lineage fight across time to protect a celestial treasure crafted from a fallen star.",
    poster_path: '/posters/205.svg',
    backdrop_path: '/posters/205.svg',
    vote_average: 7.9,
    vote_count: 8500,
    release_date: '2024-09-12',
    genre_ids: [28, 12, 14],
    popularity: 91,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["2024 Onam Megahit","Tovino Thomas Triple Role","Folklore & Visual Spectacle","Verified Kannada Audio on JioHotstar"],
    director: "Jithin Laal",
    cast: ["Tovino Thomas","Krithi Shetty","Aishwarya Rajesh","Surabhi Lakshmi"],
    trailer_youtube_id: '2kF_31wP2zM',
    scene_clip: "Maniyan Ancient Heist at Chyothikkavu (30s Spotlight)",
    hero_name: "Tovino Thomas",
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/a-r-m/1271337988',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/a-r-m/1271337988',
        },
      ],
    },
  },
  {
    id: 206,
    title: "Vikram",
    original_title: "Vikram",
    original_language: 'ta',
    overview: "A black-ops squad led by Amar investigates a series of murders committed by a masked vigilante syndicate, uncovering ties to an undercover operative thought to be dead.",
    poster_path: '/posters/206.svg',
    backdrop_path: '/posters/206.svg',
    vote_average: 8.3,
    vote_count: 21000,
    release_date: '2022-06-03',
    genre_ids: [28, 53, 80],
    popularity: 95,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Lokesh Cinematic Universe (LCU)","Kamal Haasan Comeback Titan","Fahadh Faasil & Vijay Sethupathi Masterclass","Verified Kannada Audio on JioHotstar"],
    director: "Lokesh Kanagaraj",
    cast: ["Kamal Haasan","Vijay Sethupathi","Fahadh Faasil","Suriya (Rolex)"],
    trailer_youtube_id: 'OKBMCLzuvtw',
    scene_clip: "Aarambikalangala & Rolex Warning Climax (30s Spotlight)",
    hero_name: "Kamal Haasan",
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/vikram/1260106598',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/vikram/1260106598',
        },
      ],
    },
  },
  {
    id: 207,
    title: "Sita Ramam",
    original_title: "Sita Ramam",
    original_language: 'te',
    overview: "Lieutenant Ram, an orphaned army officer serving at Kashmir border, receives an anonymous letter from a girl named Sita Mahalakshmi. Love blossoms across distances and borders.",
    poster_path: '/posters/207.svg',
    backdrop_path: '/posters/207.svg',
    vote_average: 8.6,
    vote_count: 14200,
    release_date: '2022-08-05',
    genre_ids: [18, 10749],
    popularity: 93,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Pure Poetic Romance","Dulquer Salmaan & Mrunal Thakur","Timeless Music by Vishal Chandrashekhar","Verified Kannada Audio on JioHotstar"],
    director: "Hanu Raghavapudi",
    cast: ["Dulquer Salmaan","Mrunal Thakur","Rashmika Mandanna","Sumanth"],
    trailer_youtube_id: 'L3n3YFj3d9U',
    scene_clip: "Ram Writing Letter to Sita (30s Spotlight)",
    hero_name: "Dulquer Salmaan",
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/sita-ramam/1260117823',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/sita-ramam/1260117823',
        },
      ],
    },
  },
  {
    id: 208,
    title: "Bramayugam",
    original_title: "Bramayugam",
    original_language: 'ml',
    overview: "In 17th-century Malabar, Thevan, a folk singer escaping slavery, stumbles upon a mysterious, decaying manor ruled by Kodumon Potti, where sinister secrets bind him to the house.",
    poster_path: '/posters/208.svg',
    backdrop_path: '/posters/208.svg',
    vote_average: 8.2,
    vote_count: 10500,
    release_date: '2024-02-15',
    genre_ids: [27, 9648, 53],
    popularity: 90,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Monochrome B&W',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Mammootty Iconic Negative Masterpiece","Unique Black-and-White Atmospheric Horror","Folklore Chaathan Mystery","Verified Kannada Audio on SonyLIV"],
    director: "Rahul Sadasivan",
    cast: ["Mammootty","Arjun Ashokan","Sidharth Bharathan","Amalda Liz"],
    trailer_youtube_id: '9B6E1oQeP8g',
    scene_clip: "Kodumon Potti Dice Game & Laughter (30s Spotlight)",
    hero_name: "Mammootty",
    watchProviders: {
      link: 'https://www.sonyliv.com/movies/bramayugam-kannada-1000268815',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com/movies/bramayugam-kannada-1000268815',
        },
      ],
    },
  },
  {
    id: 209,
    title: "Boxing Parampare (Sarpatta)",
    original_title: "Sarpatta Parambarai",
    original_language: 'ta',
    overview: "In 1970s North Madras, Kabilan, a young port worker belonging to the Sarpatta clan, rises above systemic oppression and personal setbacks to reclaim his clan’s boxing legacy.",
    poster_path: '/posters/209.svg',
    backdrop_path: '/posters/209.svg',
    vote_average: 8.4,
    vote_count: 12500,
    release_date: '2021-07-22',
    genre_ids: [28, 18],
    popularity: 88,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Pa. Ranjith Directorial Powerhouse","Arya Peak Physical Transformation","Rangan Vaathiyar Iconic Role","Verified Kannada Audio on Zee5"],
    director: "Pa. Ranjith",
    cast: ["Arya","Pasupathy","John Kokken","Dushara Vijayan"],
    trailer_youtube_id: '3zM5p0e8K0A',
    scene_clip: "Kabilan Ring Entrance & Boxing Climax Round (30s Spotlight)",
    hero_name: "Arya",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/boxing-parampare/0-0-1z5113598',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/boxing-parampare/0-0-1z5113598',
        },
      ],
    },
  },
  {
    id: 210,
    title: "Har Har Mahadev",
    original_title: "Har Har Mahadev",
    original_language: 'mr',
    overview: "The inspiring historical tale of Baji Prabhu Deshpande and Chhatrapati Shivaji Maharaj, culminating in the heroic last stand at the Battle of Pavan Khind.",
    poster_path: '/posters/210.svg',
    backdrop_path: '/posters/210.svg',
    vote_average: 7.7,
    vote_count: 4900,
    release_date: '2022-10-25',
    genre_ids: [28, 18, 36],
    popularity: 80,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["First Marathi Film Dubbed in Kannada","Sharad Kelkar Magnificent Performance","Authentic Maratha History","Verified Kannada Audio on Zee5"],
    director: "Abhijeet Deshpande",
    cast: ["Sharad Kelkar","Subodh Bhave","Amruta Khanvilkar"],
    trailer_youtube_id: '4F5k8d9K2c0',
    scene_clip: "Pavan Khind Pass Defense War Cry (30s Spotlight)",
    hero_name: "Sharad Kelkar",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/har-har-mahadev-kannada/0-0-1z5264530',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/har-har-mahadev-kannada/0-0-1z5264530',
        },
      ],
    },
  },
  {
    id: 301,
    title: "Premalu",
    original_title: "Premalu",
    original_language: 'ml',
    overview: "Sachin, an ordinary boy planning to leave for the UK, joins a GATE coaching center in Hyderabad. He falls head-over-heels for Reenu, an IT employee with high standards.",
    poster_path: '/posters/301.svg',
    backdrop_path: '/posters/301.svg',
    vote_average: 8.2,
    vote_count: 11000,
    release_date: '2024-02-09',
    genre_ids: [35, 10749],
    popularity: 94,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["2024 Rom-Com Sensation","Pure Feel-Good Laughs","Superb Youth Relatability","Verified Kannada Audio on JioHotstar"],
    director: "Girish A. D.",
    cast: ["Naslen","Mamitha Baiju","Sangeeth Prathap","Shyam Mohan"],
    trailer_youtube_id: 'c1B0b1B1b1B',
    scene_clip: "Aadi Intro & JK Rowling Dialogue (30s Spotlight)",
    hero_name: "Naslen",
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/premalu/1260171290',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/premalu/1260171290',
        },
      ],
    },
  },
  {
    id: 302,
    title: "Manjummel Boys",
    original_title: "Manjummel Boys",
    original_language: 'ml',
    overview: "A bunch of tight-knit friends from a small town in Kochi visit Kodaikanal. When one falls deep into the Guna Caves, the others risk everything in a historic rescue.",
    poster_path: '/posters/302.svg',
    backdrop_path: '/posters/302.svg',
    vote_average: 8.7,
    vote_count: 16500,
    release_date: '2024-02-22',
    genre_ids: [18, 53, 12],
    popularity: 97,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["2024 Industry Record Breaker","Real-Life Survival Story","Unbreakable Brotherhood","Verified Kannada Audio on JioHotstar"],
    director: "Chidambaram",
    cast: ["Soubin Shahir","Sreenath Bhasi","Balu Varghese","Ganapathi"],
    trailer_youtube_id: 'm1F3_G5eH1w',
    scene_clip: "Kuttan Descending into Devil Kitchen (30s Spotlight)",
    hero_name: "Soubin Shahir",
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/manjummel-boys/1260173892',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/manjummel-boys/1260173892',
        },
      ],
    },
  },
  {
    id: 303,
    title: "Gargi",
    original_title: "Gargi",
    original_language: 'ta',
    overview: "A determined school teacher fights single-handedly against a hostile society and judicial system to prove the innocence of her elderly father accused of a heinous crime.",
    poster_path: '/posters/303.svg',
    backdrop_path: '/posters/303.svg',
    vote_average: 8.4,
    vote_count: 7600,
    release_date: '2022-07-15',
    genre_ids: [18, 53, 80],
    popularity: 87,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Sai Pallavi Tour-de-force Performance","Realistic Legal Thriller","Emotionally Gripping Twist","Verified Kannada Audio on SonyLIV"],
    director: "Gautham Ramachandran",
    cast: ["Sai Pallavi","Kaali Venkat","R. S. Shivaji","Kavitha Bharathi"],
    trailer_youtube_id: 'xJ8LhF4qDqE',
    scene_clip: "Courtroom Cross-Examination by Indrans (30s Spotlight)",
    hero_name: "Sai Pallavi",
    watchProviders: {
      link: 'https://www.sonyliv.com/movies/gargi-1000183912',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com/movies/gargi-1000183912',
        },
      ],
    },
  },
  {
    id: 304,
    title: "Por Thozhil",
    original_title: "Por Thozhil",
    original_language: 'ta',
    overview: "A bookish, timid rookie police officer is paired with a battle-hardened reclusive veteran detective to catch an elusive serial killer targeting young women in Trichy.",
    poster_path: '/posters/304.svg',
    backdrop_path: '/posters/304.svg',
    vote_average: 8.2,
    vote_count: 9800,
    release_date: '2023-06-09',
    genre_ids: [80, 53, 9648],
    popularity: 90,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Benchmark Indian Serial Killer Thriller","Masterful Pacing & Scripting","Sarathkumar & Ashok Selvan Chemistry","Verified Kannada Audio on SonyLIV"],
    director: "Vignesh Raja",
    cast: ["R. Sarathkumar","Ashok Selvan","Nikhila Vimal","P. L. Thenappan"],
    trailer_youtube_id: '9B6E1oQeP8g',
    scene_clip: "Abandoned Warehouse Trap Investigation (30s Spotlight)",
    hero_name: "R. Sarathkumar",
    watchProviders: {
      link: 'https://www.sonyliv.com/movies/por-thozhil-1000224198',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com/movies/por-thozhil-1000224198',
        },
      ],
    },
  },
  {
    id: 305,
    title: "2018: Everyone is a Hero",
    original_title: "2018",
    original_language: 'ml',
    overview: "During the unprecedented 2018 Kerala floods, citizens from across religion, caste, and social standing come together in an extraordinary display of human compassion and courage.",
    poster_path: '/posters/305.svg',
    backdrop_path: '/posters/305.svg',
    vote_average: 8.5,
    vote_count: 13500,
    release_date: '2023-05-05',
    genre_ids: [18, 53],
    popularity: 92,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["India Official Entry to Oscars 2024","Heart-wrenching True Humanitarian Spirit","Realistic Practical Flood Effects","Verified Kannada Audio on SonyLIV"],
    director: "Jude Anthany Joseph",
    cast: ["Tovino Thomas","Kunchacko Boban","Asif Ali","Vineeth Sreenivasan"],
    trailer_youtube_id: 'R9x8P0kO5tE',
    scene_clip: "Fishermen Boats Arriving in Submerged City (30s Spotlight)",
    hero_name: "Tovino Thomas",
    watchProviders: {
      link: 'https://www.sonyliv.com/movies/2018-1000220192',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com/movies/2018-1000220192',
        },
      ],
    },
  },
  {
    id: 306,
    title: "Balagam",
    original_title: "Balagam",
    original_language: 'te',
    overview: "Following the death of an elderly patriarch in rural Telangana, petty disputes among family members threaten to disrupt ancient funeral traditions and true closure.",
    poster_path: '/posters/306.svg',
    backdrop_path: '/posters/306.svg',
    vote_average: 8.3,
    vote_count: 6200,
    release_date: '2023-03-03',
    genre_ids: [18, 35, 10751],
    popularity: 83,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: 'Full HD 1080p • Stereo',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Global Film Festival Winner","Deeply Emotional Family Realism","Heartfelt Music & Rural Culture","Verified Kannada Audio on JioHotstar"],
    director: "Venu Yeldandi",
    cast: ["Priyadarshi","Kavya Kalyanram","Sudhakar Reddy","Roopa Lakshmi"],
    trailer_youtube_id: 'c1B0b1B1b1B',
    scene_clip: "Crows Feeding Ritual & Family Reunion (30s Spotlight)",
    hero_name: "Priyadarshi",
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/balagam/1260136912',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/balagam/1260136912',
        },
      ],
    },
  },
  {
    id: 307,
    title: "Adiyae",
    original_title: "Adiyae",
    original_language: 'ta',
    overview: "A dejected young man wishing to end his life stumbles into an alternate universe where everything in life is inverted — including his teenage love story.",
    poster_path: '/posters/307.svg',
    backdrop_path: '/posters/307.svg',
    vote_average: 7.2,
    vote_count: 4100,
    release_date: '2023-08-25',
    genre_ids: [35, 10749, 878],
    popularity: 79,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Unique Multiverse Romantic Comedy","Hilarious Pop-Culture Spoofs","G.V. Prakash Music & Acting","Verified Kannada Audio on SonyLIV"],
    director: "Vignesh Karthick",
    cast: ["G. V. Prakash Kumar","Gouri G. Kishan","Venkat Prabhu"],
    trailer_youtube_id: 'm1F3_G5eH1w',
    scene_clip: "Parallel Universe Television News Comedy (30s Spotlight)",
    hero_name: "G. V. Prakash Kumar",
    watchProviders: {
      link: 'https://www.sonyliv.com/movies/adiyae-kannada-1000242025',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com/movies/adiyae-kannada-1000242025',
        },
      ],
    },
  },
  {
    id: 308,
    title: "Sirf Ek Bandaa Kaafi Hai",
    original_title: "Sirf Ek Bandaa Kaafi Hai",
    original_language: 'hi',
    overview: "A courageous, ordinary sessions court lawyer wages a solitary, five-year legal war against a powerful, politically connected godman to deliver justice to a minor girl.",
    poster_path: '/posters/308.svg',
    backdrop_path: '/posters/308.svg',
    vote_average: 8.3,
    vote_count: 9100,
    release_date: '2023-05-23',
    genre_ids: [18, 80],
    popularity: 88,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Manoj Bajpayee Career-Best Performance","Riveting Realistic Courtroom Drama","Standing Ovation Monologue","Verified Kannada Audio on Zee5"],
    director: "Apoorv Singh Karki",
    cast: ["Manoj Bajpayee","Vipin Sharma","Adrija Sinha","Surya Mohan Kulshreshtha"],
    trailer_youtube_id: '2kF_31wP2zM',
    scene_clip: "Final Nuance Argument on POCSO Act (30s Spotlight)",
    hero_name: "Manoj Bajpayee",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/sirf-ek-bandaa-kaafi-hai/0-0-1z5359029',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/sirf-ek-bandaa-kaafi-hai/0-0-1z5359029',
        },
      ],
    },
  },
  {
    id: 309,
    title: "Tarla",
    original_title: "Tarla",
    original_language: 'hi',
    overview: "The heartwarming true story of Tarla Dalal, an ordinary homemaker who revolutionized Indian home cooking, cookbooks, and culinary shows through her passion.",
    poster_path: '/posters/309.svg',
    backdrop_path: '/posters/309.svg',
    vote_average: 7.3,
    vote_count: 3900,
    release_date: '2023-07-07',
    genre_ids: [18, 35],
    popularity: 78,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: 'Full HD 1080p • Stereo',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Inspiring Female Entrepreneur Journey","Wholesome Family Feel-Good","Huma Qureshi Charming Performance","Verified Kannada Audio on Zee5"],
    director: "Piyush Gupta",
    cast: ["Huma Qureshi","Sharib Hashmi","Bharati Achrekar"],
    trailer_youtube_id: 'OKBMCLzuvtw',
    scene_clip: "Tarla First Cooking Class Breakthrough (30s Spotlight)",
    hero_name: "Huma Qureshi",
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/tarla/0-0-1z5368704',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/tarla/0-0-1z5368704',
        },
      ],
    },
  },
  {
    id: 310,
    title: "Zara Hatke Zara Bachke",
    original_title: "Zara Hatke Zara Bachke",
    original_language: 'hi',
    overview: "Kapil and Somya are a happily married middle-class couple living in a joint family who stage a fake divorce just to become eligible for a government housing scheme.",
    poster_path: '/posters/310.svg',
    backdrop_path: '/posters/310.svg',
    vote_average: 7.1,
    vote_count: 6700,
    release_date: '2023-06-02',
    genre_ids: [35, 10749, 10751],
    popularity: 84,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Box Office Romantic Comedy Hit","Middle-Class Family Realities","Chartbuster Music","Verified Kannada Audio on JioCinema"],
    director: "Laxman Utekar",
    cast: ["Vicky Kaushal","Sara Ali Khan","Inaamulhaq","Rakesh Bedi"],
    trailer_youtube_id: 'L3n3YFj3d9U',
    scene_clip: "Courtroom Fake Divorce Arguments Comedy (30s Spotlight)",
    hero_name: "Vicky Kaushal",
    watchProviders: {
      link: 'https://www.jiocinema.com/movies/zara-hatke-zara-bachke/3947812',
      flatrate: [
        {
          provider_id: 220,
          provider_name: 'JioCinema',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.jiocinema.com/movies/zara-hatke-zara-bachke/3947812',
        },
      ],
    },
  },
  {
    id: 311,
    title: "Bhediya",
    original_title: "Bhediya",
    original_language: 'hi',
    overview: "Bhaskar, a road contractor in the forests of Arunachal Pradesh, is bitten by a mythical shape-shifting wolf. As strange changes occur in him, his friends try to save him.",
    poster_path: '/posters/311.svg',
    backdrop_path: '/posters/311.svg',
    vote_average: 7.2,
    vote_count: 8200,
    release_date: '2022-11-25',
    genre_ids: [35, 27],
    popularity: 86,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed)',
    subtitles: 'English',
    highlights: ["Maddock Supernatural Comedy Universe","Varun Dhawan & Abhishek Banerjee Laughs","Top-Tier VFX & Ecology Message","Verified Kannada Audio on JioCinema"],
    director: "Amar Kaushik",
    cast: ["Varun Dhawan","Kriti Sanon","Abhishek Banerjee","Deepak Dobriyal"],
    trailer_youtube_id: 'c8_yJ_54q_E',
    scene_clip: "Full Moon Night Transformation in Forest (30s Spotlight)",
    hero_name: "Varun Dhawan",
    watchProviders: {
      link: 'https://www.jiocinema.com/movies/bhediya/3782914',
      flatrate: [
        {
          provider_id: 220,
          provider_name: 'JioCinema',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.jiocinema.com/movies/bhediya/3782914',
        },
      ],
    },
  },
  {
    id: 501,
    title: "Kantara: Chapter 1",
    original_title: "Kantara: Chapter 1",
    original_language: 'kn',
    overview: "The prequel to the sensational blockbuster Kantara, diving deep into the origins of the sacred forest, the divine Kadamba-era folklore, and the fierce deity Panjurli Daiva.",
    poster_path: '/posters/501.svg',
    backdrop_path: '/posters/501.svg',
    vote_average: 0,
    vote_count: 0,
    release_date: '2025-10-02',
    genre_ids: [28, 14, 18],
    popularity: 99.5,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'Anticipated U/A',
    quality: 'Theatrical Release First • 4K IMAX',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Pre-OTT Theatrical Tracking","Rishab Shetty & Hombale Films","Kadamba Empire Mythological Origins","Worldwide Theatrical Oct 2, 2025"],
    director: "Rishab Shetty",
    cast: ["Rishab Shetty"],
    trailer_youtube_id: 'i8VjN_QO2c8',
    scene_clip: "Kadamba Era Axe & Fire Teaser (30s Spotlight)",
    hero_name: "Rishab Shetty",
    isUpcoming: true,
    watchProviders: {
      link: '',
      flatrate: [],
    },
  },
  {
    id: 502,
    title: "Uttarakaanda",
    original_title: "Uttarakaanda",
    original_language: 'kn',
    overview: "A gritty gangster epic set in the rugged landscapes of North Karnataka, revolving around Gabru Sathya and the violent clash of regional mafia clans.",
    poster_path: '/posters/502.svg',
    backdrop_path: '/posters/502.svg',
    vote_average: 0,
    vote_count: 0,
    release_date: '2025-12-15',
    genre_ids: [28, 80, 18],
    popularity: 92,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'Anticipated A',
    quality: 'Theatrical Release First • Full HD',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ["Pre-OTT Theatrical Tracking","Dr. Shiva Rajkumar & Daali Dhananjaya","North Karnataka Native Dialect","Amit Trivedi Musical Score"],
    director: "Rohit Padaki",
    cast: ["Daali Dhananjaya","Dr. Shiva Rajkumar","Aishwarya Rajesh","Bhavana Menon"],
    trailer_youtube_id: '3iCgH_mE49k',
    scene_clip: "Gabru Sathya North Karnataka Dialect Teaser (30s Spotlight)",
    hero_name: "Daali Dhananjaya",
    isUpcoming: true,
    watchProviders: {
      link: '',
      flatrate: [],
    },
  },
];

// Helper functions for catalog queries
export function getMovieById(id: number): (MovieWithProviders & { isUpcoming?: boolean }) | undefined {
  return CURATED_MOVIES.find((m) => m.id === id);
}

export function getMoviesByHero(heroName: string): (MovieWithProviders & { isUpcoming?: boolean })[] {
  return CURATED_MOVIES.filter((m) => m.hero_name?.toLowerCase().includes(heroName.toLowerCase()));
}

export function getKannadaOriginals(): (MovieWithProviders & { isUpcoming?: boolean })[] {
  return CURATED_MOVIES.filter((m) => m.isKannada);
}

export function getKannadaDubbed(): (MovieWithProviders & { isUpcoming?: boolean })[] {
  return CURATED_MOVIES.filter((m) => !m.isKannada && m.hasKannadaDub);
}

export function getMoviesByProvider(providerId: number): (MovieWithProviders & { isUpcoming?: boolean })[] {
  return CURATED_MOVIES.filter((m) =>
    m.watchProviders?.flatrate?.some((p) => p.provider_id === providerId)
  );
}

export function searchCatalog(query: string): (MovieWithProviders & { isUpcoming?: boolean })[] {
  const q = query.toLowerCase();
  return CURATED_MOVIES.filter(
    (m) =>
      m.title.toLowerCase().includes(q) ||
      m.original_title.toLowerCase().includes(q) ||
      m.hero_name?.toLowerCase().includes(q) ||
      m.director?.toLowerCase().includes(q) ||
      m.cast?.some((c) => c.toLowerCase().includes(q))
  );
}

export function getCatalogMovieDetails(id: number): MovieDetails | undefined {
  const m = getMovieById(id);
  if (!m) return undefined;
  return {
    ...m,
    genres: m.genre_ids.map((gid) => ({ id: gid, name: gid === 35 ? 'Comedy' : gid === 28 ? 'Action' : gid === 10749 ? 'Romance' : 'Drama' })),
    runtime: 145,
    tagline: m.highlights?.[0] || '',
    status: m.isUpcoming ? 'In Production / Releasing Soon' : 'Released',
    budget: 0,
    revenue: 0,
    homepage: m.watchProviders?.link || '',
    imdb_id: `tt${m.id}`,
    spoken_languages: [{ english_name: 'Kannada', iso_639_1: 'kn', name: 'ಕನ್ನಡ' }],
    production_countries: [{ iso_3166_1: 'IN', name: 'India' }],
  };
}

