// Curated Database of Kannada Originals & Kannada Dubbed Movies
// Available on Indian OTTs: JioHotstar (122), Zee5 (232), SonyLIV (237), JioCinema (220)
// Focus: Realistic, Comedy, Family, Feel-Good, Drama (Excluded unrealistic spy/war fighter movies)
// 100% of titles have VERIFIED Kannada Audio (Original or Dubbed) and Direct Movie Links.

import { MovieWithProviders, MovieDetails } from './types';
import { GENRES, LANGUAGES } from './constants';

export const CURATED_MOVIES: MovieWithProviders[] = [
  // ─── KANNADA ORIGINALS ──────────────────────────────────────────
  {
    id: 101,
    title: '777 Charlie',
    original_title: '777 Charlie',
    original_language: LANGUAGES.KANNADA,
    overview: 'Dharma is stuck in a rut with his negative and lonely lifestyle, spending each day in the comfort of his loneliness. A spirited labrador pup named Charlie enters his life and leads him on an emotional, transformational road trip to Himachal Pradesh.',
    poster_path: '/posters/101.jpg',
    backdrop_path: '/posters/101.jpg',
    vote_average: 8.8,
    vote_count: 14500,
    release_date: '2022-06-10',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA, GENRES.FAMILY, GENRES.ADVENTURE],
    popularity: 98.5,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 7+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['National Award Winner', 'Feel-Good Family Entertainer', 'Top Rated Kannada Film', 'Emotional Journey'],
    director: 'Kiranraj K.',
    cast: ['Rakshit Shetty', 'Sangeetha Sringeri', 'Raj B. Shetty', 'Danish Sait', 'Bobby Simha'],
    trailer_youtube_id: 'c8_yJ_54q_E',
    scene_clip: 'Dharma & Charlie Idli Share Moment (30s Preview)',
    watchProviders: {
      link: 'https://www.jiocinema.com/movies/777-charlie/3762294',
      flatrate: [
        {
          provider_id: 220,
          provider_name: 'JioCinema',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.jiocinema.com/movies/777-charlie/3762294',
        },
      ],
    },
  },
  {
    id: 102,
    title: 'Sapta Sagaradaache Ello - Side A',
    original_title: 'Sapta Sagaradaache Ello - Side A',
    original_language: LANGUAGES.KANNADA,
    overview: 'Manu and Priya cherish their passionate love and dream of a bright future together. But their dreams take a tragic turn when Manu takes an unexpected decision to fulfill their ambitions.',
    poster_path: '/posters/102.svg',
    backdrop_path: '/posters/102.svg',
    vote_average: 8.4,
    vote_count: 8900,
    release_date: '2023-09-01',
    genre_ids: [GENRES.DRAMA, GENRES.ROMANCE],
    popularity: 92.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Realistic Romance', 'Poetic Storytelling', 'Critically Acclaimed', 'Chartbuster Music'],
    director: 'Hemanth M. Rao',
    cast: ['Rakshit Shetty', 'Rukmini Vasanth', 'Achyuth Kumar', 'Pavitra Lokesh'],
    trailer_youtube_id: '1kE43-Mv7iI',
    scene_clip: 'Priya & Manu Ocean Dream by the Window (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/sapta-sagaradaache-ello-side-a/0-0-1z5435987',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/sapta-sagaradaache-ello-side-a/0-0-1z5435987',
        },
      ],
    },
  },
  {
    id: 103,
    title: 'Sapta Sagaradaache Ello - Side B',
    original_title: 'Sapta Sagaradaache Ello - Side B',
    original_language: LANGUAGES.KANNADA,
    overview: 'Ten years after the events of Side A, Manu walks out of prison trying to put his life together while dealing with unresolved emotions and discovering Priya’s current life.',
    poster_path: '/posters/103.svg',
    backdrop_path: '/posters/103.svg',
    vote_average: 8.2,
    vote_count: 7300,
    release_date: '2023-11-17',
    genre_ids: [GENRES.DRAMA, GENRES.ROMANCE],
    popularity: 88.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Emotional Drama', 'Grounded Realism', 'Award-Winning Performance'],
    director: 'Hemanth M. Rao',
    cast: ['Rakshit Shetty', 'Rukmini Vasanth', 'Chaithra J. Achar', 'Ramesh Indira'],
    trailer_youtube_id: 'f87iNfV0Q5Y',
    scene_clip: 'Manu Sees Surabhi & Old Echoes (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/sapta-sagaradaache-ello-side-b/0-0-1z5456789',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/sapta-sagaradaache-ello-side-b/0-0-1z5456789',
        },
      ],
    },
  },
  {
    id: 104,
    title: 'Hostel Hudugaru Bekagiddare',
    kannadaTitle: 'ಹಾಸ್ಟೆಲ್ ಹುಡುಗರು ಬೇಕಾಗಿದ್ದಾರೆ',
    original_title: 'Hostel Hudugaru Bekagiddare',
    original_language: LANGUAGES.KANNADA,
    overview: 'A chaotic, hilarious comedy following a group of engineering students living in a boys hostel when a sudden tragedy strikes the night before their final exam submission.',
    poster_path: '/posters/104.jpg',
    backdrop_path: '/posters/104.jpg',
    vote_average: 8.1,
    vote_count: 6500,
    release_date: '2023-07-21',
    genre_ids: [GENRES.COMEDY, GENRES.MYSTERY],
    popularity: 91.4,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Stereo',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Superhit Comedy', 'Relatable Hostel Life', 'Cult Youth Favorite'],
    director: 'Nithin Krishnamurthy',
    cast: ['Prajwal BP', 'Rakesh Rajkumar', 'Shrivatsa Shyam', 'Tejas Jayanna Urs', 'Rishab Shetty'],
    trailer_youtube_id: '_x1G5fHnJ5Q',
    scene_clip: 'Warden Room Midnight Panic Sequence (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/hostel-hudugaru-bekagiddare/0-0-1z5412345',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/hostel-hudugaru-bekagiddare/0-0-1z5412345',
        },
      ],
    },
  },
  {
    id: 105,
    title: 'Daredevil Musthafa',
    original_title: 'Daredevil Musthafa',
    original_language: LANGUAGES.KANNADA,
    overview: 'Based on K.P. Poornachandra Tejaswi’s story, a heartwarming, realistic comedy-drama revolving around a Muslim student in a small-town college who attempts to win over his skeptical classmates through a cricket match.',
    poster_path: '/posters/105.jpg',
    backdrop_path: '/posters/105.jpg',
    vote_average: 8.5,
    vote_count: 5100,
    release_date: '2023-05-19',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA, GENRES.FAMILY],
    popularity: 85.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Clean Family Comedy', 'Based on KP Poornachandra Tejaswi', 'Community Harmony', 'Realistic Small-Town'],
    director: 'Shashank Soghal',
    cast: ['Shishir Baikady', 'Aditya Ashoka', 'Abhay', 'Supreeth Bharadwaj', 'Mandya Ramesh'],
    trailer_youtube_id: 'rDmgjS_V4Z0',
    scene_clip: 'College Cricket Match Climax Excitement (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/daredevil-musthafa/0-0-1z5398765',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/daredevil-musthafa/0-0-1z5398765',
        },
      ],
    },
  },
  {
    id: 106,
    title: 'Ratnan Prapancha',
    original_title: 'Ratnan Prapancha',
    original_language: LANGUAGES.KANNADA,
    overview: 'Ratnakara, an average middle-class man who is fed up with his nagging mother, embarks on a journey across India to find his biological roots, leading to hilarious and heartwarming discoveries.',
    poster_path: '/posters/106.svg',
    backdrop_path: '/posters/106.svg',
    vote_average: 8.3,
    vote_count: 7200,
    release_date: '2021-10-22',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA, GENRES.FAMILY],
    popularity: 82.5,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Heartwarming Family Story', 'Laugh-Out-Loud Moments', 'Dhananjaya Best Acting', 'Mother-Son Bond'],
    director: 'Rohit Padaki',
    cast: ['Dhananjaya', 'Umashree', 'Reba Monica John', 'Pramod Panju', 'Anu Prabhakar'],
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/ratnan-prapancha/0-0-1z5298123',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/ratnan-prapancha/0-0-1z5298123',
        },
      ],
    },
  },
  {
    id: 107,
    title: 'Badava Rascal',
    original_title: 'Badava Rascal',
    original_language: LANGUAGES.KANNADA,
    overview: 'A realistic middle-class youth faces societal pressures, unemployment, and romantic troubles alongside his loyal friends in Bengaluru in this lighthearted comedy entertainer.',
    poster_path: '/posters/107.svg',
    backdrop_path: '/posters/107.svg',
    vote_average: 7.6,
    vote_count: 4800,
    release_date: '2021-12-24',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA, GENRES.ROMANCE],
    popularity: 79.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Bengaluru Middle Class Life', 'Friendship Comedy', 'Dhananjaya Mass & Class'],
    director: 'Shankar Guru',
    cast: ['Dhananjaya', 'Amrutha Iyengar', 'Nagabhushana', 'Poornachandra Mysore'],
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/badava-rascal/0-0-1z5301298',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/badava-rascal/0-0-1z5301298',
        },
      ],
    },
  },
  {
    id: 108,
    title: 'Gandhada Gudi',
    original_title: 'Gandhada Gudi',
    original_language: LANGUAGES.KANNADA,
    overview: 'Dr. Puneeth Rajkumar and wildlife filmmaker Amoghavarsha embark on a wondrous journey across Karnataka’s mesmerizing natural landscapes, forests, and marine sanctuaries.',
    poster_path: '/posters/108.jpg',
    backdrop_path: '/posters/108.jpg',
    vote_average: 8.9,
    vote_count: 11200,
    release_date: '2022-10-28',
    genre_ids: [GENRES.FAMILY, GENRES.ADVENTURE, GENRES.DOCUMENTARY],
    popularity: 93.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: '4K Ultra HD • Dolby Atmos',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Appu Puneeth Rajkumar Tribute', 'Karnataka Wildlife & Heritage', 'Visual Masterpiece', 'Clean Family Film'],
    director: 'Amoghavarsha J. S.',
    cast: ['Dr. Puneeth Rajkumar', 'Amoghavarsha J. S.'],
    trailer_youtube_id: 'gP_Hh0gHq78',
    scene_clip: 'Appu Walking into Bandipur Forest (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/gandhada-gudi/1260144181',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/gandhada-gudi/1260144181',
        },
      ],
    },
  },
  {
    id: 109,
    title: 'Toby',
    original_title: 'Toby',
    original_language: LANGUAGES.KANNADA,
    overview: 'An estranged, mute man living on the fringes of society becomes a beast to protect his foster daughter from local oppressors in a coastal town.',
    poster_path: '/posters/109.svg',
    backdrop_path: '/posters/109.svg',
    vote_average: 7.7,
    vote_count: 3800,
    release_date: '2023-08-25',
    genre_ids: [GENRES.DRAMA],
    popularity: 76.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'A (18+)',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Coastal Karnataka Atmosphere', 'Raj B Shetty Powerful Acting', 'Gritty & Realistic'],
    director: 'Basil AL Chalakkal',
    cast: ['Raj B. Shetty', 'Chaithra J. Achar', 'Samyukta Hornad', 'Gopalkrishna Deshpande'],
    watchProviders: {
      link: 'https://www.sonyliv.com/movies/toby-1000244199',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com/movies/toby-1000244199',
        },
      ],
    },
  },
  {
    id: 110,
    title: 'Kaatera',
    original_title: 'Kaatera',
    original_language: LANGUAGES.KANNADA,
    overview: 'Set in the 1970s rural Karnataka, a brave blacksmith stands up against feudal landlords to help farmers claim ownership of their agricultural lands.',
    poster_path: '/posters/110.jpg',
    backdrop_path: '/posters/110.jpg',
    vote_average: 7.9,
    vote_count: 6200,
    release_date: '2023-12-29',
    genre_ids: [GENRES.DRAMA],
    popularity: 88.5,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Rural Land Reform History', 'Darshan Mass Entertainer', 'Superhit Box Office'],
    director: 'Tharun Kishore Sudhir',
    cast: ['Darshan', 'Aradhana Ram', 'Jagapathi Babu', 'Kumar Govind'],
    trailer_youtube_id: 'L0Q-5Q5v-pQ',
    scene_clip: 'Kaatera Village Blacksmith Intro (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/kaatera/0-0-1z5478901',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/kaatera/0-0-1z5478901',
        },
      ],
    },
  },

  // ─── KANNADA DUBBED — HINDI HITS ON INDIAN OTT ──────────────────
  {
    id: 201,
    title: '12th Fail',
    original_title: '12th Fail',
    original_language: LANGUAGES.HINDI,
    overview: 'Based on the real-life story of IPS officer Manoj Kumar Sharma, who hails from a small Chambal village, restarts his academic journey from scratch, and takes on the toughest civil service exams with grit and determination.',
    poster_path: '/posters/201.jpg',
    backdrop_path: '/posters/201.jpg',
    vote_average: 9.0,
    vote_count: 28000,
    release_date: '2023-10-27',
    genre_ids: [GENRES.DRAMA, GENRES.FAMILY],
    popularity: 99.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Hindi',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Inspiring True Story', 'Highest Rated Indian Film of 2023', 'Vikrant Massey Masterclass', 'Clean Family Drama'],
    director: 'Vidhu Vinod Chopra',
    cast: ['Vikrant Massey', 'Medha Shankr', 'Anant V Joshi', 'Anshumaan Pushkar'],
    trailer_youtube_id: 'we3j2Kq8QfQ',
    scene_clip: 'Manoj Kumar Sharma Interview Board Climax (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/12th-fail/1260159987',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/12th-fail/1260159987',
        },
      ],
    },
  },
  {
    id: 202,
    title: 'Zara Hatke Zara Bachke',
    original_title: 'Zara Hatke Zara Bachke',
    original_language: LANGUAGES.HINDI,
    overview: 'A middle-class married couple in Indore scheme a fake divorce to qualify for a government housing scheme under PM Awas Yojana, leading to a comedy of errors with their family.',
    poster_path: '/posters/202.jpg',
    backdrop_path: '/posters/202.jpg',
    vote_average: 7.2,
    vote_count: 5300,
    release_date: '2023-06-02',
    genre_ids: [GENRES.COMEDY, GENRES.ROMANCE, GENRES.FAMILY],
    popularity: 81.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Hindi',
    subtitles: 'English',
    highlights: ['Family Comedy', 'Relatable Housing Struggle', 'Vicky Kaushal & Sara Ali Khan'],
    director: 'Laxman Utekar',
    cast: ['Vicky Kaushal', 'Sara Ali Khan', 'Inaamulhaq', 'Sushmita Mukherjee'],
    trailer_youtube_id: '4F4s_Z5B6jY',
    scene_clip: 'Kapil & Somya Indore Home Hunting Comedy (30s Preview)',
    watchProviders: {
      link: 'https://www.jiocinema.com/movies/zara-hatke-zara-bachke/3947812',
      flatrate: [
        {
          provider_id: 220,
          provider_name: 'JioCinema',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.jiocinema.com/movies/zara-hatke-zara-bachke/3947812',
        },
      ],
    },
  },
  {
    id: 203,
    title: 'Sam Bahadur',
    original_title: 'Sam Bahadur',
    original_language: LANGUAGES.HINDI,
    overview: 'The inspiring true life story of India’s first Field Marshal Sam Manekshaw, chronicling his four-decade military career, his strategic leadership during the 1971 war, and his legendary charisma.',
    poster_path: '/posters/203.svg',
    backdrop_path: '/posters/203.svg',
    vote_average: 8.0,
    vote_count: 8100,
    release_date: '2023-12-01',
    genre_ids: [GENRES.DRAMA, GENRES.HISTORY],
    popularity: 86.5,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Hindi',
    subtitles: 'English',
    highlights: ['True History', 'Vicky Kaushal Transformative Role', 'National Pride'],
    director: 'Meghna Gulzar',
    cast: ['Vicky Kaushal', 'Fatima Sana Shaikh', 'Sanya Malhotra', 'Govind Namdev'],
    trailer_youtube_id: '1a-AkyA-q0s',
    scene_clip: 'Field Marshal Cabinet Meeting Strategy (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/sam-bahadur/0-0-1z5467812',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/sam-bahadur/0-0-1z5467812',
        },
      ],
    },
  },
  {
    id: 204,
    title: 'Sirf Ek Bandaa Kaafi Hai',
    original_title: 'Sirf Ek Bandaa Kaafi Hai',
    original_language: LANGUAGES.HINDI,
    overview: 'An ordinary session court lawyer single-handedly takes on the powerful legal team of an influential godman in a relentless 5-year pursuit of truth and justice for a minor girl.',
    poster_path: '/posters/204.jpg',
    backdrop_path: '/posters/204.jpg',
    vote_average: 8.3,
    vote_count: 9400,
    release_date: '2023-05-23',
    genre_ids: [GENRES.DRAMA],
    popularity: 87.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Hindi',
    subtitles: 'English',
    highlights: ['Gripping Courtroom Realism', 'Manoj Bajpayee Tour de Force', 'Inspiring Truth Fight'],
    director: 'Apoorv Singh Karki',
    cast: ['Manoj Bajpayee', 'Vipin Sharma', 'Surya Mohan Kulshrestha', 'Kaustav Sinha'],
    trailer_youtube_id: 'M1i0aT9U03M',
    scene_clip: 'Advocate Solanki Supreme Court Arguments (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/sirf-ek-bandaa-kaafi-hai/0-0-1z5389123',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/sirf-ek-bandaa-kaafi-hai/0-0-1z5389123',
        },
      ],
    },
  },
  {
    id: 205,
    title: 'Tarla',
    original_title: 'Tarla',
    original_language: LANGUAGES.HINDI,
    overview: 'A feel-good, heartwarming biographical drama recounting the life journey of Tarla Dalal, who broke societal boundaries to become India’s most beloved home chef and cookbook author.',
    poster_path: '/posters/205.svg',
    backdrop_path: '/posters/205.svg',
    vote_average: 7.5,
    vote_count: 3600,
    release_date: '2023-07-07',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA, GENRES.FAMILY],
    popularity: 74.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: 'Full HD 1080p',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Hindi',
    subtitles: 'English',
    highlights: ['Inspiring Woman Entrepreneur', 'Family Warmth & Food', 'Huma Qureshi Outstanding'],
    director: 'Piyush Gupta',
    cast: ['Huma Qureshi', 'Sharib Hashmi', 'Bharati Achrekar', 'Amarjeet Singh'],
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/tarla/0-0-1z5409124',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/tarla/0-0-1z5409124',
        },
      ],
    },
  },
  {
    id: 206,
    title: 'Bhediya',
    original_title: 'Bhediya',
    original_language: LANGUAGES.HINDI,
    overview: 'A road contractor working on an infrastructure project in the forests of Arunachal Pradesh gets bitten by a mythical wolf, beginning a comic and thrilling transformation.',
    poster_path: '/posters/206.svg',
    backdrop_path: '/posters/206.svg',
    vote_average: 7.3,
    vote_count: 7900,
    release_date: '2022-11-25',
    genre_ids: [GENRES.COMEDY, GENRES.FANTASY],
    popularity: 80.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Hindi',
    subtitles: 'English',
    highlights: ['Horror Comedy Universe', 'Arunachal Forest Visuals', 'Varun Dhawan & Abhishek Banerjee Comedy'],
    director: 'Amar Kaushik',
    cast: ['Varun Dhawan', 'Kriti Sanon', 'Abhishek Banerjee', 'Deepak Dobriyal'],
    watchProviders: {
      link: 'https://www.jiocinema.com/movies/bhediya/3782914',
      flatrate: [
        {
          provider_id: 220,
          provider_name: 'JioCinema',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.jiocinema.com/movies/bhediya/3782914',
        },
      ],
    },
  },

  // ─── KANNADA DUBBED — MALAYALAM & TAMIL FEEL-GOOD HITS ──────────
  {
    id: 301,
    title: 'Premalu',
    original_title: 'Premalu',
    original_language: LANGUAGES.MALAYALAM,
    overview: 'A charming, laugh-out-loud romantic comedy set in Hyderabad following Sachin, who falls head-over-heels for Reenu while preparing for his higher education.',
    poster_path: '/posters/301.jpg',
    backdrop_path: '/posters/301.jpg',
    vote_average: 8.6,
    vote_count: 14200,
    release_date: '2024-02-09',
    genre_ids: [GENRES.COMEDY, GENRES.ROMANCE],
    popularity: 96.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Malayalam',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['All-Time Blockbuster Rom-Com', 'Non-Stop Laughter', 'Hyderabad IT Youth Vibe'],
    director: 'Girish A. D.',
    cast: ['Naslen K. Gafoor', 'Mamitha Baiju', 'Sangeeth Prathap', 'Shyam Mohan'],
    trailer_youtube_id: '3g9N7F2p-w8',
    scene_clip: 'Sachin & Reenu Hyderabad Pub Introduction (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/premalu/1260171290',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/premalu/1260171290',
        },
      ],
    },
  },
  {
    id: 302,
    title: 'Manjummel Boys',
    original_title: 'Manjummel Boys',
    original_language: LANGUAGES.MALAYALAM,
    overview: 'Based on an incredible true rescue event, a group of close-knit friends from Kochi embark on a trip to Kodaikanal where one of them accidentally slips into the perilous Guna Caves.',
    poster_path: '/posters/302.svg',
    backdrop_path: '/posters/302.svg',
    vote_average: 8.7,
    vote_count: 19800,
    release_date: '2024-02-22',
    genre_ids: [GENRES.DRAMA, GENRES.ADVENTURE],
    popularity: 98.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Malayalam',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Historic Box Office Record', 'Real Friendship & Bravery', 'Nail-biting Survival'],
    director: 'Chidambaram',
    cast: ['Soubin Shahir', 'Sreenath Bhasi', 'Balu Varghese', 'Ganapathi', 'Jean Paul Lal'],
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/manjummel-boys/1260173892',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/manjummel-boys/1260173892',
        },
      ],
    },
  },
  {
    id: 303,
    title: 'Gargi',
    original_title: 'Gargi',
    original_language: LANGUAGES.TAMIL,
    overview: 'A young school teacher fights tooth and nail with the assistance of a stuttering advocate to clear her father’s name when he is unexpectedly implicated in a sensitive criminal case.',
    poster_path: '/posters/303.jpg',
    backdrop_path: '/posters/303.jpg',
    vote_average: 8.2,
    vote_count: 5400,
    release_date: '2022-07-15',
    genre_ids: [GENRES.DRAMA, GENRES.MYSTERY],
    popularity: 81.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Tamil',
    subtitles: 'English',
    highlights: ['Sai Pallavi Stellar Performance', 'Emotional Father-Daughter Bond', 'Courtroom Masterclass'],
    director: 'Gautham Ramachandran',
    cast: ['Sai Pallavi', 'Kaali Venkat', 'R. S. Shivaji', 'Saravanan'],
    trailer_youtube_id: 'xV88N4y2y5A',
    scene_clip: 'Sai Pallavi Classroom Search Dialogue (30s Preview)',
    watchProviders: {
      link: 'https://www.sonyliv.com/movies/gargi-1000183912',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com/movies/gargi-1000183912',
        },
      ],
    },
  },
  {
    id: 304,
    title: 'Por Thozhil',
    original_title: 'Por Thozhil',
    original_language: LANGUAGES.TAMIL,
    overview: 'A brilliant, academically gifted rookie cop teams up with an abrasive veteran officer to track down an elusive serial killer targeting women across regional towns.',
    poster_path: '/posters/304.svg',
    backdrop_path: '/posters/304.svg',
    vote_average: 8.4,
    vote_count: 8200,
    release_date: '2023-06-09',
    genre_ids: [GENRES.MYSTERY, GENRES.DRAMA],
    popularity: 88.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Tamil',
    subtitles: 'English',
    highlights: ['One of India\'s Best Whodunits', 'Sarath Kumar & Ashok Selvan', 'Realistic Investigation'],
    director: 'Vignesh Raja',
    cast: ['R. Sarathkumar', 'Ashok Selvan', 'Nikhila Vimal', 'P. L. Thenappan'],
    watchProviders: {
      link: 'https://www.sonyliv.com/movies/por-thozhil-1000224198',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com/movies/por-thozhil-1000224198',
        },
      ],
    },
  },
  {
    id: 305,
    title: '2018: Everyone is a Hero',
    original_title: '2018',
    original_language: LANGUAGES.MALAYALAM,
    overview: 'Ordinary citizens from diverse walks of life put aside their differences, unite courageously, and conduct daring rescue operations during the catastrophic 2018 Kerala floods.',
    poster_path: '/posters/305.svg',
    backdrop_path: '/posters/305.svg',
    vote_average: 8.5,
    vote_count: 12100,
    release_date: '2023-05-05',
    genre_ids: [GENRES.DRAMA, GENRES.FAMILY],
    popularity: 90.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: '4K Ultra HD • Dolby Atmos',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Malayalam',
    subtitles: 'English',
    highlights: ['India\'s Official Oscar Entry', 'True Humanity in Crisis', 'Tovino Thomas & Asif Ali'],
    director: 'Jude Anthany Joseph',
    cast: ['Tovino Thomas', 'Kunchacko Boban', 'Asif Ali', 'Vineeth Sreenivasan', 'Aparna Balamurali'],
    watchProviders: {
      link: 'https://www.sonyliv.com/movies/2018-1000220192',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com/movies/2018-1000220192',
        },
      ],
    },
  },

  // ─── KANNADA DUBBED — TELUGU FEEL-GOOD & FAMILY ENTERTAINERS ───
  {
    id: 401,
    title: 'Sita Ramam',
    original_title: 'Sita Ramam',
    original_language: LANGUAGES.TELUGU,
    overview: 'An orphaned army lieutenant serving in Kashmir begins receiving affectionate letters from a woman named Sita Mahalakshmi. Their deep bond transcends time, distance, and borders.',
    poster_path: '/posters/401.jpg',
    backdrop_path: '/posters/401.jpg',
    vote_average: 8.6,
    vote_count: 16500,
    release_date: '2022-08-05',
    genre_ids: [GENRES.ROMANCE, GENRES.DRAMA],
    popularity: 93.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Telugu',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Timeless Love Story', 'Dulquer & Mrunal Chemistry', 'Sensational Melodies'],
    director: 'Hanu Raghavapudi',
    cast: ['Dulquer Salmaan', 'Mrunal Thakur', 'Rashmika Mandanna', 'Sumanth'],
    trailer_youtube_id: 'l2R_7p5k1wM',
    scene_clip: 'Ram Writing Letter to Sita (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/sita-ramam/1260117823',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/sita-ramam/1260117823',
        },
      ],
    },
  },
  {
    id: 402,
    title: 'Hanu-Man',
    original_title: 'Hanu-Man',
    original_language: LANGUAGES.TELUGU,
    overview: 'An ordinary villager in the fictional village of Anjanadri unexpectedly gains superpowers of Lord Hanuman and steps up to protect his people from a greedy corporate villain.',
    poster_path: '/posters/402.svg',
    backdrop_path: '/posters/402.svg',
    vote_average: 8.1,
    vote_count: 15400,
    release_date: '2024-01-12',
    genre_ids: [GENRES.FANTASY, GENRES.COMEDY, GENRES.FAMILY],
    popularity: 94.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Telugu',
    subtitles: 'English',
    highlights: ['Clean Family Fantasy', 'Underdog Superhero', 'Epic Climax'],
    director: 'Prasanth Varma',
    cast: ['Teja Sajja', 'Amritha Aiyer', 'Varalaxmi Sarathkumar', 'Vinay Rai'],
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/hanu-man/0-0-1z5512984',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/hanu-man/0-0-1z5512984',
        },
        {
          provider_id: 220,
          provider_name: 'JioCinema',
          logo_path: '',
          display_priority: 2,
          directUrl: 'https://www.jiocinema.com/movies/hanu-man/3941829',
        },
      ],
    },
  },
  {
    id: 403,
    title: 'Balagam',
    original_title: 'Balagam',
    original_language: LANGUAGES.TELUGU,
    overview: 'Set in a rural Telangana village, the passing of a respected family patriarch unearths long-simmering domestic squabbles, forcing estranged relatives to confront customs and reunite.',
    poster_path: '/posters/403.svg',
    backdrop_path: '/posters/403.svg',
    vote_average: 8.4,
    vote_count: 6700,
    release_date: '2023-03-03',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA, GENRES.FAMILY],
    popularity: 82.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: 'Full HD 1080p',
    audio: 'ಕನ್ನಡ (Dubbed Available) • Telugu',
    subtitles: 'English',
    highlights: ['Deep Village Roots', 'Family Reunion Emotions', 'Heart-touching Realism'],
    director: 'Venu Yeldandi',
    cast: ['Priyadarshi Pulikonda', 'Kavya Kalyanram', 'Roopa Lakshmi', 'Muralidhar Goud'],
    watchProviders: {
      link: 'https://www.hotstar.com/in/movies/balagam/1260136912',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in/movies/balagam/1260136912',
        },
      ],
    },
  },

  // ─── UPCOMING KANNADA & DUBBED RELEASES ──────────────────────────
  {
    id: 501,
    title: 'Kantara: Chapter 1',
    original_title: 'Kantara: Chapter 1',
    original_language: LANGUAGES.KANNADA,
    overview: 'A prequel detailing the ancient origin of the mythical demigod Panjurli and the Kadamba dynasty era in the coastal Karnataka heartlands.',
    poster_path: '/posters/501.jpg',
    backdrop_path: '/posters/501.jpg',
    vote_average: 8.9,
    vote_count: 520,
    release_date: '2025-10-02',
    genre_ids: [GENRES.DRAMA, GENRES.MYSTERY],
    popularity: 99.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • IMAX Enhanced',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Kadamba Dynasty Era', 'Rishab Shetty Masterpiece', 'Ancient Panjurli Legend'],
    director: 'Rishab Shetty',
    cast: ['Rishab Shetty'],
    trailer_youtube_id: 'w6n3T4bM8uQ',
    scene_clip: 'First Glimpse Torchlight Kadamba Roar (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  {
    id: 502,
    title: 'Uttarakaanda',
    original_title: 'Uttarakaanda',
    original_language: LANGUAGES.KANNADA,
    overview: 'A rustic, earthy retro gangster comedy-drama set in North Karnataka, directed by Rohit Padaki and starring Dhananjaya.',
    poster_path: '/posters/502.svg',
    backdrop_path: '/posters/502.svg',
    vote_average: 8.3,
    vote_count: 310,
    release_date: '2025-05-15',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA],
    popularity: 90.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['North Karnataka Dialect', 'Dhananjaya & Shivarajkumar', 'Retro Earthy Atmosphere'],
    director: 'Rohit Padaki',
    cast: ['Dhananjaya', 'Shivarajkumar', 'Aishwarya Rajesh', 'Diganth'],
    trailer_youtube_id: '6zE6X6_6L0k',
    scene_clip: 'North Karnataka Desert Action Teaser (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },

  // ─── SUPERSTAR SPOTLIGHTS (KANNADA DUBBED) ────────────────────────
  // Jr. NTR (RRR, Devara)
  {
    id: 601,
    title: 'RRR',
    original_title: 'RRR',
    kannadaTitle: 'ಆರ್ ಆರ್ ಆರ್',
    original_language: LANGUAGES.TELUGU,
    overview: 'A fearless revolutionary and an officer in the British force, who once were best friends, join forces to chart a legendary path against tyrannical rulers. Blockbuster Kannada dubbed version featuring Jr. NTR and Ram Charan.',
    poster_path: '/posters/601.jpg',
    backdrop_path: '/posters/601.jpg',
    vote_average: 8.8,
    vote_count: 18500,
    release_date: '2022-03-25',
    genre_ids: [GENRES.DRAMA, GENRES.ADVENTURE],
    popularity: 99.5,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Academy Award Winner', 'Jr. NTR Bheem Intro', 'Blockbuster Multi-Starrer', 'High Voltage Action'],
    director: 'S. S. Rajamouli',
    cast: ['N. T. Rama Rao Jr.', 'Ram Charan', 'Alia Bhatt', 'Ajay Devgn'],
    trailer_youtube_id: 'NgBoMJy386M',
    hero_name: 'Jr. NTR',
    scene_clip: 'Komuram Bheemudo Intro & Fight Scene (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com/movies/details/rrr/0-0-1z5146581',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com/movies/details/rrr/0-0-1z5146581',
        },
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 2,
          directUrl: 'https://www.hotstar.com/in/movies/rrr/1260108122',
        },
      ],
    },
  },
  {
    id: 602,
    title: 'Devara: Part 1',
    original_title: 'Devara: Part 1',
    kannadaTitle: 'ದೇವರ: ಪಾರ್ಟ್ ೧',
    original_language: LANGUAGES.TELUGU,
    overview: 'An epic coastal saga about a courageous man who embarks on a perilous journey into the treacherous waters to safeguard the lives and dignity of his people against smuggling tyrants.',
    poster_path: '/posters/602.svg',
    backdrop_path: '/posters/602.svg',
    vote_average: 7.8,
    vote_count: 8200,
    release_date: '2024-09-27',
    genre_ids: [GENRES.DRAMA, GENRES.ADVENTURE],
    popularity: 96.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Jr. NTR Dual Role', 'Massive Sea Battle Action', 'Anirudh BGM Score', 'Kannada Dubbed Release'],
    director: 'Koratala Siva',
    cast: ['N. T. Rama Rao Jr.', 'Saif Ali Khan', 'Janhvi Kapoor', 'Shruti Marathe'],
    trailer_youtube_id: '7v3m43k_6L4',
    hero_name: 'Jr. NTR',
    scene_clip: 'Red Sea Coastal Night Encounter (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  // Thalapathy Vijay (Leo, Varisu)
  {
    id: 603,
    title: 'Leo',
    original_title: 'Leo',
    kannadaTitle: 'ಲಿಯೋ',
    original_language: LANGUAGES.TAMIL,
    overview: 'Parthiban is a mild-mannered cafe owner in Theog, Himachal Pradesh, living a peaceful life with his family. When gangsters arrive claiming he is former cartel enforcer Leo Das, chaos ensues.',
    poster_path: '/posters/603.svg',
    backdrop_path: '/posters/603.svg',
    vote_average: 7.9,
    vote_count: 12400,
    release_date: '2023-10-19',
    genre_ids: [GENRES.DRAMA, GENRES.THRILLER],
    popularity: 97.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Thalapathy Vijay Swag', 'Lokesh Cinematic Universe', 'High-Octane Cafe Sequence', 'Anirudh Sensational OST'],
    director: 'Lokesh Kanagaraj',
    cast: ['Thalapathy Vijay', 'Trisha Krishnan', 'Sanjay Dutt', 'Arjun Sarja'],
    trailer_youtube_id: 'Po3jVh2CAT8',
    hero_name: 'Thalapathy Vijay',
    scene_clip: 'Cafe Action Sequence & Climax Reveal (30s Preview)',
    watchProviders: {
      link: 'https://www.sonyliv.com',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com',
        },
      ],
    },
  },
  {
    id: 604,
    title: 'Varisu',
    original_title: 'Varisu',
    kannadaTitle: 'ವಾರಿಸು',
    original_language: LANGUAGES.TAMIL,
    overview: 'Vijay Rajendran is the happy-go-lucky estranged youngest son of a business tycoon. When his father is diagnosed with a terminal illness, Vijay steps in to take over the empire and reunite his fractured family.',
    poster_path: '/posters/604.svg',
    backdrop_path: '/posters/604.svg',
    vote_average: 7.4,
    vote_count: 7600,
    release_date: '2023-01-11',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA, GENRES.FAMILY],
    popularity: 91.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Feel-Good Family Entertainer', 'Thalapathy Vijay Comedy Timing', 'Heartwarming Reunion', 'Superhit Songs'],
    director: 'Vamshi Paidipally',
    cast: ['Thalapathy Vijay', 'Rashmika Mandanna', 'R. Sarathkumar', 'Jayasudha'],
    trailer_youtube_id: '9fux9G45i4I',
    hero_name: 'Thalapathy Vijay',
    scene_clip: 'Boardroom Family Comedy & Monologue (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },
  // Mahesh Babu (Guntur Kaaram, Sarkaru Vaari Paata)
  {
    id: 605,
    title: 'Guntur Kaaram',
    original_title: 'Guntur Kaaram',
    kannadaTitle: 'ಗುಂಟೂರು ಖಾರಂ',
    original_language: LANGUAGES.TELUGU,
    overview: 'Ramana, a charismatic man from Guntur, is asked to sign a document severing all ties with his politician mother who abandoned him years ago. He refuses and seeks to uncover the truth.',
    poster_path: '/posters/605.svg',
    backdrop_path: '/posters/605.svg',
    vote_average: 7.3,
    vote_count: 6500,
    release_date: '2024-01-12',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA, GENRES.FAMILY],
    popularity: 92.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Super Star Mahesh Babu Energy', 'Mother-Son Emotional Thread', 'Trivikram Punch Dialogues', 'Kurchi Madathapetti Dance'],
    director: 'Trivikram Srinivas',
    cast: ['Mahesh Babu', 'Sreeleela', 'Meenakshi Chaudhary', 'Ramya Krishnan', 'Prakash Raj'],
    trailer_youtube_id: 'dyQkFh2oNFs',
    hero_name: 'Mahesh Babu',
    scene_clip: 'Bidi Swag & Mother Encounter Dialogue (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  {
    id: 606,
    title: 'Sarkaru Vaari Paata',
    original_title: 'Sarkaru Vaari Paata',
    kannadaTitle: 'ಸರ್ಕಾರು ವಾರಿ ಪಾಟ',
    original_language: LANGUAGES.TELUGU,
    overview: 'After being conned by the woman he loves in Miami, a financier travels to India to recover his money from an unscrupulous politician, triggering a fierce fight against corporate banking fraud.',
    poster_path: '/posters/606.svg',
    backdrop_path: '/posters/606.svg',
    vote_average: 7.2,
    vote_count: 5900,
    release_date: '2022-05-12',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA],
    popularity: 88.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Mahesh Babu Vintage Comedy', 'Miami Romance & Fun', 'Thaman Musical Hit', 'Relentless Money Pursuit'],
    director: 'Parasuram',
    cast: ['Mahesh Babu', 'Keerthy Suresh', 'Samuthirakani', 'Vennela Kishore'],
    trailer_youtube_id: 'd9_18c-y32E',
    hero_name: 'Mahesh Babu',
    scene_clip: 'Miami Loan Recovery Comedy Encounter (30s Preview)',
    watchProviders: {
      link: 'https://www.jiocinema.com',
      flatrate: [
        {
          provider_id: 220,
          provider_name: 'JioCinema',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.jiocinema.com',
        },
      ],
    },
  },
  // Victory Venkatesh (Saindhav, F3)
  {
    id: 607,
    title: 'Saindhav',
    original_title: 'Saindhav',
    kannadaTitle: 'ಸೈಂಧವ್',
    original_language: LANGUAGES.TELUGU,
    overview: 'A quiet single father and port crane operator is forced to return to his lethal past when his beloved daughter is diagnosed with a rare fatal condition requiring an exorbitantly costly injection.',
    poster_path: '/posters/607.svg',
    backdrop_path: '/posters/607.svg',
    vote_average: 7.5,
    vote_count: 5100,
    release_date: '2024-01-13',
    genre_ids: [GENRES.DRAMA, GENRES.THRILLER],
    popularity: 89.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Victory Venkatesh 75th Milestone Film', 'Tender Father-Daughter Bond', 'Nawazuddin Siddiqui Faceoff', 'Emotional Climax'],
    director: 'Sailesh Kolanu',
    cast: ['Venkatesh Daggubati', 'Shraddha Srinath', 'Nawazuddin Siddiqui', 'Arya', 'Andrea Jeremiah'],
    trailer_youtube_id: 'R9xLw5e8oHQ',
    hero_name: 'Victory Venkatesh',
    scene_clip: 'Father Daughter Clinic & Container Fight (30s Preview)',
    watchProviders: {
      link: 'https://www.sonyliv.com',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com',
        },
      ],
    },
  },
  {
    id: 608,
    title: 'F3: Fun and Frustration',
    original_title: 'F3: Fun and Frustration',
    kannadaTitle: 'ಎಫ್ ೩: ಫನ್ & ಫ್ರಸ್ಟ್ರೇಷನ್',
    original_language: LANGUAGES.TELUGU,
    overview: 'Two quirky men struggling with hilarious personal physical limitations and chronic greed try to enter a lavish palace by pretending to be the heirs of an eccentric billionaire industrialist.',
    poster_path: '/posters/608.svg',
    backdrop_path: '/posters/608.svg',
    vote_average: 7.6,
    vote_count: 6700,
    release_date: '2022-05-27',
    genre_ids: [GENRES.COMEDY, GENRES.FAMILY],
    popularity: 93.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Non-Stop Family Laugh Riots', 'Venkatesh Night Blindness Comedy', 'Varun Tej Stammer Antics', 'Total Fun Package'],
    director: 'Anil Ravipudi',
    cast: ['Venkatesh Daggubati', 'Varun Tej', 'Tamannaah Bhatia', 'Mehreen Pirzada', 'Sunil'],
    trailer_youtube_id: 'B0k0jGq2qF4',
    hero_name: 'Victory Venkatesh',
    scene_clip: 'Night Blindness Hotel Laugh Sequence (30s Preview)',
    watchProviders: {
      link: 'https://www.sonyliv.com',
      flatrate: [
        {
          provider_id: 237,
          provider_name: 'SonyLIV',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.sonyliv.com',
        },
      ],
    },
  },

  // Prabhas (Salaar, Radhe Shyam)
  {
    id: 609,
    title: 'Salaar: Part 1 - Ceasefire',
    original_title: 'Salaar: Part 1 - Ceasefire',
    kannadaTitle: 'ಸಲಾರ್ (ಕನ್ನಡ)',
    original_language: LANGUAGES.TELUGU,
    overview: 'A gang leader makes a promise to a dying friend and takes on other criminal gangs in the dystopian city of Khansaar. High-octane action drama directed by Prashanth Neel, featuring Prabhas in an intense avatar with full Kannada audio track.',
    poster_path: '/posters/609.svg',
    backdrop_path: '/posters/609.svg',
    vote_average: 8.1,
    vote_count: 14200,
    release_date: '2023-12-22',
    genre_ids: [GENRES.DRAMA, GENRES.ADVENTURE],
    popularity: 98.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'A',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Prabhas & Prashanth Neel Collab', 'Massive Khansaar World', 'High Adrenaline Action', 'Kannada Dubbed Audio'],
    director: 'Prashanth Neel',
    cast: ['Prabhas', 'Prithviraj Sukumaran', 'Shruti Haasan', 'Jagapathi Babu'],
    trailer_youtube_id: '4GPvYMKtrtI',
    hero_name: 'Prabhas',
    scene_clip: 'Khansaar Border Gates & Deva Intro (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  {
    id: 610,
    title: 'Radhe Shyam',
    original_title: 'Radhe Shyam',
    kannadaTitle: 'ರಾಧೆ ಶ್ಯಾಮ್ (ಕನ್ನಡ)',
    original_language: LANGUAGES.TELUGU,
    overview: 'In 1970s Europe, a world-renowned palmist Vikramaditya who does not believe in love or relationships falls deeply for a doctor named Prerana, challenging the very destiny he foretells.',
    poster_path: '/posters/610.svg',
    backdrop_path: '/posters/610.svg',
    vote_average: 7.1,
    vote_count: 6100,
    release_date: '2022-03-11',
    genre_ids: [GENRES.DRAMA, GENRES.ROMANCE],
    popularity: 87.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Prabhas Vintage Romantic Look', 'Scenic European Locales', 'Destiny vs Love Theme', 'Kannada Audio on Zee5'],
    director: 'Radha Krishna Kumar',
    cast: ['Prabhas', 'Pooja Hegde', 'Bhagyashree', 'Krishnam Raju'],
    trailer_youtube_id: '4b_j23kZ6B4',
    hero_name: 'Prabhas',
    scene_clip: 'Vikramaditya Palmistry Reading Scene (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },
  // Allu Arjun (Pushpa, Ala Vaikunthapurramuloo)
  {
    id: 611,
    title: 'Pushpa: The Rise',
    original_title: 'Pushpa: The Rise',
    kannadaTitle: 'ಪುಷ್ಪ: ದಿ ರೈಸ್ (ಕನ್ನಡ)',
    original_language: LANGUAGES.TELUGU,
    overview: 'A coolie rises through the ranks of a red sandalwood smuggling syndicate in the Seshachalam Hills of Andhra Pradesh, defying tyrannical bosses and a corrupt IPS officer with daring swagger.',
    poster_path: '/posters/611.svg',
    backdrop_path: '/posters/611.svg',
    vote_average: 8.2,
    vote_count: 17800,
    release_date: '2021-12-17',
    genre_ids: [GENRES.DRAMA, GENRES.THRILLER],
    popularity: 98.5,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Iconic Allu Arjun Performance', 'National Award Winner', 'Chartbuster Kannada Songs', 'Sukumar Direction'],
    director: 'Sukumar',
    cast: ['Allu Arjun', 'Rashmika Mandanna', 'Fahadh Faasil', 'Sunil', 'Anasuya'],
    trailer_youtube_id: 'pKctpnpsC8Y',
    hero_name: 'Allu Arjun',
    scene_clip: 'Thaggedhe Le Dialogue & Seshachalam Forest (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 2,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  {
    id: 612,
    title: 'Ala Vaikunthapurramuloo',
    original_title: 'Ala Vaikunthapurramuloo',
    kannadaTitle: 'ಅಲಾ ವೈಕುಂಠಪುರಮುಲೋ (ಕನ್ನಡ)',
    original_language: LANGUAGES.TELUGU,
    overview: 'Bantu grows up facing constant neglect from his strict father Valmiki, unaware that he was switched at birth with the son of an ultra-wealthy businessman. When he learns the truth, he sets out to protect his biological family.',
    poster_path: '/posters/612.svg',
    backdrop_path: '/posters/612.svg',
    vote_average: 7.8,
    vote_count: 9800,
    release_date: '2020-01-12',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA, GENRES.FAMILY],
    popularity: 94.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Allu Arjun Supreme Style & Dance', 'Heartwarming Family Values', 'Trivikram Clean Comedy', 'Thaman Sensational Music'],
    director: 'Trivikram Srinivas',
    cast: ['Allu Arjun', 'Pooja Hegde', 'Tabu', 'Jayaram', 'Murali Sharma', 'Sushanth'],
    trailer_youtube_id: '2r1V_wY_2xU',
    hero_name: 'Allu Arjun',
    scene_clip: 'Boardroom Dance & Pitch Meeting (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },
  // Ram Charan (Vinaya Vidheya Rama)
  {
    id: 613,
    title: 'Vinaya Vidheya Rama',
    original_title: 'Vinaya Vidheya Rama',
    kannadaTitle: 'ವಿನಯ ವಿಧೇಯ ರಾಮ (ಕನ್ನಡ)',
    original_language: LANGUAGES.TELUGU,
    overview: 'Four orphaned brothers raise their youngest brother Ram Konidela with great affection. When an honest election officer brother is threatened by a dreaded Bihar crime boss, Ram rises up to protect his family.',
    poster_path: '/posters/613.svg',
    backdrop_path: '/posters/613.svg',
    vote_average: 7.0,
    vote_count: 5300,
    release_date: '2019-01-11',
    genre_ids: [GENRES.DRAMA, GENRES.FAMILY],
    popularity: 86.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Mega Power Star Ram Charan Energy', 'Strong Brotherly Bond', 'Boyapati High Voltage Action', 'Popular Kannada Dub on Hotstar'],
    director: 'Boyapati Srinu',
    cast: ['Ram Charan', 'Kiara Advani', 'Vivek Oberoi', 'Prashanth', 'Sneha'],
    trailer_youtube_id: 'yPjB2Kz3vE4',
    hero_name: 'Ram Charan',
    scene_clip: 'Ram Konidela Family Defense Dialogue (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  // Dulquer Salmaan (Lucky Baskhar)
  {
    id: 614,
    title: 'Lucky Baskhar',
    original_title: 'Lucky Baskhar',
    kannadaTitle: 'ಲಕ್ಕಿ ಭಾಸ್ಕರ್ (ಕನ್ನಡ)',
    original_language: LANGUAGES.TELUGU,
    overview: 'A modest bank cashier burdened by rising middle-class debts gets drawn into a lucrative world of financial laundering and the Indian stock market frenzy of the early 1990s.',
    poster_path: '/posters/614.svg',
    backdrop_path: '/posters/614.svg',
    vote_average: 8.4,
    vote_count: 8900,
    release_date: '2024-10-31',
    genre_ids: [GENRES.DRAMA, GENRES.THRILLER],
    popularity: 96.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Dulquer Salmaan Masterclass Acting', 'Gripping 1990s Financial Story', 'Critically Acclaimed Hit', 'Kannada Audio on Zee5'],
    director: 'Venky Atluri',
    cast: ['Dulquer Salmaan', 'Meenakshi Chaudhary', 'Ramki', 'Hyper Aadi'],
    trailer_youtube_id: 'q_21H_1W0rU',
    hero_name: 'Dulquer Salmaan',
    scene_clip: '1992 Bombay Stock Exchange Cash Counting (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },
  // Tovino Thomas (ARM)
  {
    id: 615,
    title: 'ARM: Ajayante Randam Moshanam',
    original_title: 'Ajayante Randam Moshanam',
    kannadaTitle: 'ಎ.ಆರ್.ಎಮ್ (ಕನ್ನಡ)',
    original_language: LANGUAGES.MALAYALAM,
    overview: 'Spanning three generations in northern Kerala across 1900, 1950, and 1992, three heroes Maniyan, Kunjikelu, and Ajayan fight to protect a celestial treasure that landed from the heavens.',
    poster_path: '/posters/615.svg',
    backdrop_path: '/posters/615.svg',
    vote_average: 8.0,
    vote_count: 7300,
    release_date: '2024-09-12',
    genre_ids: [GENRES.DRAMA, GENRES.ADVENTURE],
    popularity: 93.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Tovino Thomas Triple Role', 'Visually Stunning Folklore', 'Dibu Ninan Thomas Epic Score', 'Kannada Dubbed on Hotstar'],
    director: 'Jithin Laal',
    cast: ['Tovino Thomas', 'Krithi Shetty', 'Aishwarya Rajesh', 'Surabhi Lakshmi', 'Basil Joseph'],
    trailer_youtube_id: 'd6yR7b8w7yM',
    hero_name: 'Tovino Thomas',
    scene_clip: 'Maniyan Ancient Chyothikkavu Heist (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  // Ranbir Kapoor (Brahmāstra)
  {
    id: 616,
    title: 'Brahmāstra: Part One – Shiva',
    original_title: 'Brahmāstra: Part One – Shiva',
    kannadaTitle: 'ಬ್ರಹ್ಮಾಸ್ತ್ರ: ಭಾಗ ಒಂದು – ಶಿವ (ಕನ್ನಡ)',
    original_language: LANGUAGES.HINDI,
    overview: 'Shiva, a young DJ in Mumbai, discovers his supernatural connection to the divine element of fire and the ancient secret society Brahmānsh protecting the world from dark forces.',
    poster_path: '/posters/616.svg',
    backdrop_path: '/posters/616.svg',
    vote_average: 7.5,
    vote_count: 15600,
    release_date: '2022-09-09',
    genre_ids: [GENRES.DRAMA, GENRES.ADVENTURE, GENRES.FANTASY],
    popularity: 95.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Spectacular VFX & Astraverse', 'Sanjith Hegde Kannada Songs', 'Amitabh Bachchan & Nagarjuna', 'Kannada Audio on Hotstar'],
    director: 'Ayan Mukerji',
    cast: ['Ranbir Kapoor', 'Alia Bhatt', 'Amitabh Bachchan', 'Nagarjuna Akkineni', 'Mouni Roy'],
    trailer_youtube_id: 'm0_Xj_v2V0k',
    hero_name: 'Ranbir Kapoor',
    scene_clip: 'Agnyastra Awakening & Temple Confrontation (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },

  // ─── LATEST 2024-2025 RELEASES & EXPANDED DISCOVERY ────────────────
  {
    id: 701,
    title: 'Blink',
    original_title: 'Blink',
    kannadaTitle: 'ಬ್ಲಿಂಕ್',
    original_language: LANGUAGES.KANNADA,
    overview: 'A mysterious man reveals to a struggling theatre student named Apoorva that his estranged father, whom he believed dead for decades, is actually alive and capable of controlling time blinks.',
    poster_path: '/posters/701.svg',
    backdrop_path: '/posters/701.svg',
    vote_average: 8.3,
    vote_count: 5800,
    release_date: '2024-03-08',
    genre_ids: [GENRES.DRAMA, GENRES.MYSTERY],
    popularity: 94.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Mind-Bending Time Travel Thriller', 'Oedipus Greek Tragedy Twist', 'Critically Acclaimed Kannada Gem'],
    director: 'Srinidhi Bengaluru',
    cast: ['Dheekshith Shetty', 'Chaithra J. Achar', 'Mandara Battalahalli', 'Gopal Deshpande'],
    trailer_youtube_id: 'iH7bQ9U8h6A',
    scene_clip: 'First Time Blink Demonstration Scene (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },
  {
    id: 702,
    title: 'Shakhahaari',
    original_title: 'Shakhahaari',
    kannadaTitle: 'ಶಾಖಾಹಾರಿ',
    original_language: LANGUAGES.KANNADA,
    overview: 'In a misty, quiet Malnad hill town, Subbanna, a kind-hearted traditional vegetarian hotelier, discovers a wounded fugitive hiding in his kitchen, leading to a complex game with a troubled police inspector.',
    poster_path: '/posters/702.svg',
    backdrop_path: '/posters/702.svg',
    vote_average: 8.2,
    vote_count: 4900,
    release_date: '2024-02-16',
    genre_ids: [GENRES.DRAMA, GENRES.MYSTERY],
    popularity: 91.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Rangayana Raghu Career Best Acting', 'Atmospheric Malnad Mystery', 'Tense Kitchen Suspense'],
    director: 'Sandeep Suneel',
    cast: ['Rangayana Raghu', 'Gopalkrishna Deshpande', 'Sujay Shastry', 'Prathama Prasad'],
    trailer_youtube_id: 'p7K4zE1t5YQ',
    scene_clip: 'Subbanna Hotel Midnight Investigation (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },
  {
    id: 703,
    title: 'Bagheera',
    original_title: 'Bagheera',
    kannadaTitle: 'ಬಘೀರ',
    original_language: LANGUAGES.KANNADA,
    overview: 'Vedanth Prabhakar, an honest IPS officer frustrated by bureaucratic corruption, adopts the masked identity of Bagheera at night to bring vigilante justice to the victims of organized crime.',
    poster_path: '/posters/703.svg',
    backdrop_path: '/posters/703.svg',
    vote_average: 7.8,
    vote_count: 8900,
    release_date: '2024-10-31',
    genre_ids: [GENRES.DRAMA, GENRES.ADVENTURE],
    popularity: 97.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Story by Prashanth Neel', 'Sriimurali Intense Superhero Swag', 'Rukmini Vasanth Female Lead'],
    director: 'Dr. Suri',
    cast: ['Sriimurali', 'Rukmini Vasanth', 'Prakash Raj', 'Achuth Kumar', 'Garuda Ram'],
    trailer_youtube_id: 'Rk0bN6V-9W4',
    scene_clip: 'Bagheera Rain Sequence Mask Reveal (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  {
    id: 704,
    title: 'Ibbani Tabbida Ileyali',
    original_title: 'Ibbani Tabbida Ileyali',
    kannadaTitle: 'ಇಬ್ಬನಿ ತಬ್ಬಿದ ಇಳೆಯಲಿ',
    original_language: LANGUAGES.KANNADA,
    overview: 'A poetic, old-school romantic drama about Sidharth and Anahita, exploring their youthful college romance and their soul-stirring reunion years later in Goa.',
    poster_path: '/posters/704.svg',
    backdrop_path: '/posters/704.svg',
    vote_average: 8.1,
    vote_count: 6200,
    release_date: '2024-09-05',
    genre_ids: [GENRES.DRAMA, GENRES.ROMANCE],
    popularity: 93.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Produced by Rakshit Shetty', 'Breathtaking Visual Aesthetics', 'Soul-Stirring Melodies'],
    director: 'Chandrajith Belliappa',
    cast: ['Vihan Gowda', 'Ankita Amar', 'Mayuri Nataraja', 'Girija Shettar'],
    trailer_youtube_id: 'xV7qE8yT1nM',
    scene_clip: 'College Rain & Umbrella Monologue (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },
  {
    id: 705,
    title: 'Kotee',
    original_title: 'Kotee',
    kannadaTitle: 'ಕೋಟೆ',
    original_language: LANGUAGES.KANNADA,
    overview: 'An honest common man named Kotee dreams of earning one crore rupees legitimately to give his middle-class family dignity, but gets entangled with a powerful underworld loan shark.',
    poster_path: '/posters/705.svg',
    backdrop_path: '/posters/705.svg',
    vote_average: 7.6,
    vote_count: 4500,
    release_date: '2024-06-14',
    genre_ids: [GENRES.DRAMA],
    popularity: 88.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Dhananjaya Honest Performance', 'Realistic Middle-Class Ethics', 'Vasuki Vaibhav Music'],
    director: 'Param',
    cast: ['Dhananjaya', 'Moksha Sengupta', 'Ramesh Indira', 'Rangayana Raghu'],
    trailer_youtube_id: '7vB2c1M9w5I',
    scene_clip: 'Kotee Moral Dialogue at Bank Counter (30s Preview)',
    watchProviders: {
      link: 'https://www.jiocinema.com',
      flatrate: [
        {
          provider_id: 220,
          provider_name: 'JioCinema',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.jiocinema.com',
        },
      ],
    },
  },
  {
    id: 706,
    title: 'Roopanthara',
    original_title: 'Roopanthara',
    kannadaTitle: 'ರೂಪಾಂತರ',
    original_language: LANGUAGES.KANNADA,
    overview: 'A moving anthology exploring the human metamorphosis across five interrelated stories: an old tribal couple facing eviction, an IT worker discovering empathy, and a reformed henchman.',
    poster_path: '/posters/706.svg',
    backdrop_path: '/posters/706.svg',
    vote_average: 8.4,
    vote_count: 5300,
    release_date: '2024-07-26',
    genre_ids: [GENRES.DRAMA],
    popularity: 92.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Raj B. Shetty Screenplay & Lead', 'Philosophical Storytelling', 'Exceptional Ensemble Cast'],
    director: 'Mithilesh Edavalath',
    cast: ['Raj B. Shetty', 'Somu Kathur', 'Lekha Naidu', 'Bharat GB'],
    trailer_youtube_id: 'L0pB5n-7w4Q',
    scene_clip: 'Raj B Shetty Old Age Reflection Scene (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },
  {
    id: 707,
    title: 'Kalki 2898 AD',
    original_title: 'Kalki 2898 AD',
    kannadaTitle: 'ಕಲ್ಕಿ ೨೮೯೮ ಎ.ಡಿ (ಕನ್ನಡ)',
    original_language: LANGUAGES.TELUGU,
    overview: 'In a post-apocalyptic dystopian world 6000 years after the Mahabharata war, bounty hunter Bhairava sets out to capture a pregnant rebel carrying the hope of the universe, facing Ashwatthama in an epic clash.',
    poster_path: '/posters/707.svg',
    backdrop_path: '/posters/707.svg',
    vote_average: 8.5,
    vote_count: 24000,
    release_date: '2024-06-27',
    genre_ids: [GENRES.DRAMA, GENRES.ADVENTURE],
    popularity: 99.8,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['All-Time Record Blockbuster', 'Prabhas & Amitabh Epic Clash', 'Kamal Haasan Terrifying Avatar', 'Kannada Audio on Zee5'],
    director: 'Nag Ashwin',
    cast: ['Prabhas', 'Amitabh Bachchan', 'Kamal Haasan', 'Deepika Padukone', 'Disha Patani'],
    trailer_youtube_id: 'kQDd1AhGIHk',
    hero_name: 'Prabhas',
    scene_clip: 'Bhairava vs Ashwatthama Ancient Staff Duel (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },
  {
    id: 708,
    title: 'The Greatest of All Time (GOAT)',
    original_title: 'The Greatest of All Time',
    kannadaTitle: 'ದಿ ಗೋಟ್ (ಕನ್ನಡ)',
    original_language: LANGUAGES.TAMIL,
    overview: 'An elite anti-terrorist agent who walked away from service after an overseas tragedy is forced back into action when a rogue clone operative with his own youthful face begins hunting his family.',
    poster_path: '/posters/708.svg',
    backdrop_path: '/posters/708.svg',
    vote_average: 7.7,
    vote_count: 13500,
    release_date: '2024-09-05',
    genre_ids: [GENRES.DRAMA],
    popularity: 96.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Thalapathy Vijay Dual Role', 'Venkat Prabhu Screenplay Twists', 'Chepauk Stadium Climax Sequence'],
    director: 'Venkat Prabhu',
    cast: ['Thalapathy Vijay', 'Prashanth', 'Prabhu Deva', 'Mohan', 'Sneha', 'Meenakshi Chaudhary'],
    trailer_youtube_id: 'jxCRlebiebw',
    hero_name: 'Thalapathy Vijay',
    scene_clip: 'Youthful Clone vs Gandhi Confrontation (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },
  {
    id: 709,
    title: 'Manjummel Boys',
    original_title: 'Manjummel Boys',
    kannadaTitle: 'ಮಂಜುಮ್ಮೆಲ್ ಬಾಯ್ಸ್ (ಕನ್ನಡ)',
    original_language: LANGUAGES.MALAYALAM,
    overview: 'A group of friends from small-town Kochi travel to Kodaikanal for a vacation. When one of them slips into the infamous bottomless Guna Caves, the friends risk their own lives to mount an impossible rescue.',
    poster_path: '/posters/709.svg',
    backdrop_path: '/posters/709.svg',
    vote_average: 8.6,
    vote_count: 19800,
    release_date: '2024-02-22',
    genre_ids: [GENRES.DRAMA, GENRES.ADVENTURE],
    popularity: 98.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Highest Grossing Malayalam Film in History', 'Unbreakable Friendship Bond', 'Nail-Biting True Incident', 'Kannada Audio on Hotstar'],
    director: 'Chidambaram',
    cast: ['Soubin Shahir', 'Sreenath Bhasi', 'Balu Varghese', 'Ganapathi'],
    trailer_youtube_id: 'gXbL8Z3xX_k',
    scene_clip: 'Kuttan Descending into Devil Kitchen Cave (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  {
    id: 710,
    title: 'Aavesham',
    original_title: 'Aavesham',
    kannadaTitle: 'ಆವೇಶಂ (ಕನ್ನಡ)',
    original_language: LANGUAGES.MALAYALAM,
    overview: 'Three college engineering students in Bengaluru struggling with college seniors seek out a local gangster named Ranga for protection, only to find themselves entangled in his chaotic, hilarious underworld life.',
    poster_path: '/posters/710.svg',
    backdrop_path: '/posters/710.svg',
    vote_average: 8.3,
    vote_count: 16500,
    release_date: '2024-04-11',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA],
    popularity: 97.5,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Fahadh Faasil Unhinged Performance', 'Set in Bengaluru Streets', 'Massive Cult Comedy Fanbase', 'Kannada Audio on Hotstar'],
    director: 'Jithu Madhavan',
    cast: ['Fahadh Faasil', 'Hipzster', 'Mithun Jai Shankar', 'Roshan Shanavas', 'Sajin Gopu'],
    trailer_youtube_id: 'L0YMp3HL444',
    hero_name: 'Fahadh Faasil',
    scene_clip: 'Ranga Bar Intro & Amban Punchline Scene (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  {
    id: 711,
    title: 'Kishkindha Kaandam',
    original_title: 'Kishkindha Kaandam',
    kannadaTitle: 'ಕಿಷ್ಕಿಂಧಾ ಕಾಂಡಂ (ಕನ್ನಡ)',
    original_language: LANGUAGES.MALAYALAM,
    overview: 'Set in a monkey-inhabited forest reserve in Kerala, a forest officer and his newlywed wife uncover strange memory lapses and a missing licensed firearm connected to the groom’s ex-military father.',
    poster_path: '/posters/711.svg',
    backdrop_path: '/posters/711.svg',
    vote_average: 8.4,
    vote_count: 7800,
    release_date: '2024-09-12',
    genre_ids: [GENRES.DRAMA, GENRES.MYSTERY],
    popularity: 94.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Superhit Slow-Burn Mystery', 'Masterful Screenplay & Twists', 'Vijayraghavan Stupendous Performance'],
    director: 'Dinjith Ayyathan',
    cast: ['Asif Ali', 'Aparna Balamurali', 'Vijayraghavan', 'Jagadish'],
    trailer_youtube_id: '6zE_X77pQ9Q',
    scene_clip: 'Father Forest Diary Climax Revelation (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  {
    id: 712,
    title: 'Meiyazhagan',
    original_title: 'Meiyazhagan',
    kannadaTitle: 'ಸತ್ಯಂ ಸುಂದರಂ (ಕನ್ನಡ)',
    original_language: LANGUAGES.TAMIL,
    overview: 'Arulmozhi returns to his ancestral village after 22 years for a cousin’s wedding with bitterness in his heart, but an encounter with an exuberant, innocent relative completely transforms his outlook on life.',
    poster_path: '/posters/712.svg',
    backdrop_path: '/posters/712.svg',
    vote_average: 8.5,
    vote_count: 9100,
    release_date: '2024-09-27',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA, GENRES.FAMILY],
    popularity: 95.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Pure Feel-Good Emotional Masterpiece', 'Karthi & Arvind Swamy Synergy', 'Govind Vasantha Heavenly Score'],
    director: 'C. Prem Kumar',
    cast: ['Karthi', 'Arvind Swamy', 'Sri Divya', 'Rajkiran'],
    trailer_youtube_id: '9uB8c2x7vX4',
    hero_name: 'Karthi',
    scene_clip: 'Night Bicycle Conversation & Name Guessing (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  {
    id: 713,
    title: 'Kanguva',
    original_title: 'Kanguva',
    kannadaTitle: 'ಕಂಗುವ (ಕನ್ನಡ)',
    original_language: LANGUAGES.TAMIL,
    overview: 'A fearless tribal warrior chieftain from 1070 AD fights to protect his people against roman conquerors, whose destiny echoes 1000 years later through a modern bounty hunter.',
    poster_path: '/posters/713.svg',
    backdrop_path: '/posters/713.svg',
    vote_average: 7.4,
    vote_count: 8200,
    release_date: '2024-11-14',
    genre_ids: [GENRES.DRAMA, GENRES.ADVENTURE],
    popularity: 91.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby Atmos 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Suriya Ferocious Ancient Warrior Avatar', 'High Budget Visual Spectacle', 'Devi Sri Prasad Powerful BGM'],
    director: 'Siva',
    cast: ['Suriya', 'Bobby Deol', 'Disha Patani', 'Yogi Babu'],
    trailer_youtube_id: '34t3gN5N9Xg',
    hero_name: 'Suriya',
    scene_clip: 'Kanguva Island Fire Battle Sequence (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  {
    id: 714,
    title: 'Yuva',
    original_title: 'Yuva',
    kannadaTitle: 'ಯುವ',
    original_language: LANGUAGES.KANNADA,
    overview: 'A hot-tempered college student and national wrestler gets entangled in violent college gang feuds in Mangaluru, eventually fighting to clear his family name and restore his father’s lost pride.',
    poster_path: '/posters/714.svg',
    backdrop_path: '/posters/714.svg',
    vote_average: 7.5,
    vote_count: 6700,
    release_date: '2024-03-29',
    genre_ids: [GENRES.DRAMA],
    popularity: 90.0,
    adult: false,
    isKannada: true,
    hasKannadaDub: true,
    age_rating: 'U/A 16+',
    quality: '4K Ultra HD • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Original)',
    subtitles: 'English',
    highlights: ['Yuva Rajkumar Explosive Debut', 'Santhosh Ananddram Directorial', 'High Emotional Father-Son Climax'],
    director: 'Santhosh Ananddram',
    cast: ['Yuva Rajkumar', 'Sapthami Gowda', 'Achyuth Kumar', 'Prakash Raj'],
    trailer_youtube_id: 'k6P9w7bQ1-Q',
    scene_clip: 'Yuva Engineering College Cafeteria Fight (30s Preview)',
    watchProviders: {
      link: 'https://www.hotstar.com/in',
      flatrate: [
        {
          provider_id: 122,
          provider_name: 'JioHotstar',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.hotstar.com/in',
        },
      ],
    },
  },
  {
    id: 715,
    title: 'Swag',
    original_title: 'Swag',
    kannadaTitle: 'ಸ್ವಾಗ್ (ಕನ್ನಡ)',
    original_language: LANGUAGES.TELUGU,
    overview: 'A comedic and satirical historical saga spanning four generations of the quirky Vinjamara royal family, as multiple eccentric descendants compete to claim an immense royal inheritance.',
    poster_path: '/posters/715.svg',
    backdrop_path: '/posters/715.svg',
    vote_average: 7.6,
    vote_count: 4800,
    release_date: '2024-10-04',
    genre_ids: [GENRES.COMEDY, GENRES.DRAMA],
    popularity: 88.0,
    adult: false,
    isKannada: false,
    hasKannadaDub: true,
    age_rating: 'U/A 13+',
    quality: 'Full HD 1080p • Dolby 5.1',
    audio: 'ಕನ್ನಡ (Dubbed Available)',
    subtitles: 'English, ಕನ್ನಡ',
    highlights: ['Sree Vishnu Hilarious Multiple Roles', 'Clever Gender Satire', 'Vivek Sagar Eclectic Music'],
    director: 'Hasith Goli',
    cast: ['Sree Vishnu', 'Ritu Varma', 'Meera Jasmine', 'Daksha Nagarkar'],
    trailer_youtube_id: '4vK8m2wP_kQ',
    scene_clip: 'Vinjamara Ancestor Palace Will Reading (30s Preview)',
    watchProviders: {
      link: 'https://www.zee5.com',
      flatrate: [
        {
          provider_id: 232,
          provider_name: 'Zee5',
          logo_path: '',
          display_priority: 1,
          directUrl: 'https://www.zee5.com',
        },
      ],
    },
  },
];

// Helper to convert MovieWithProviders to MovieDetails for detail page
export function getCatalogMovieDetails(id: number): MovieDetails | null {
  const movie = CURATED_MOVIES.find((m) => m.id === id);
  if (!movie) return null;

  return {
    ...movie,
    genres: movie.genre_ids.map((gid) => ({
      id: gid,
      name:
        gid === GENRES.COMEDY
          ? 'Comedy'
          : gid === GENRES.DRAMA
          ? 'Drama'
          : gid === GENRES.FAMILY
          ? 'Family'
          : gid === GENRES.ROMANCE
          ? 'Romance'
          : gid === GENRES.MYSTERY
          ? 'Mystery'
          : gid === GENRES.ADVENTURE
          ? 'Adventure'
          : 'Feature',
    })),
    runtime: movie.id === 101 ? 164 : movie.id === 102 ? 142 : movie.id === 201 ? 147 : 135,
    tagline: movie.isKannada ? 'Watch in Original Kannada Audio' : 'Available with Kannada Dubbed Audio',
    status: 'Released',
    budget: 0,
    revenue: 0,
    homepage: movie.watchProviders?.link || '',
    imdb_id: `tt${movie.id}000`,
    spoken_languages: [
      {
        english_name: 'Kannada',
        iso_639_1: 'kn',
        name: 'ಕನ್ನಡ',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'IN',
        name: 'India',
      },
    ],
  };
}
